// Shared factual data for the trivia/knowledge games (Buzzer Royale, Higher or Lower,
// Price Is Wrong, Guesstimate, Timeline, Odd One Out, Rank It, This or That, Trivia Duel).
// Curated for canonical, stable facts only — no volatile figures (live prices/populations).
// All answers are server-side; clients never receive the answer key for the active question.

function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; }
  return a;
}

// ---- Multiple choice: { q, choices: [4], answer: index } ----
export const MULTIPLE_CHOICE = [
  { q: 'Which planet is the largest in our solar system?', choices: ['Saturn', 'Jupiter', 'Neptune', 'Earth'], answer: 1 },
  { q: 'What is the chemical symbol for gold?', choices: ['Go', 'Gd', 'Au', 'Ag'], answer: 2 },
  { q: 'How many continents are there on Earth?', choices: ['5', '6', '7', '8'], answer: 2 },
  { q: 'Which gas do plants absorb from the atmosphere?', choices: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], answer: 2 },
  { q: 'What is the largest ocean on Earth?', choices: ['Atlantic', 'Indian', 'Arctic', 'Pacific'], answer: 3 },
  { q: 'Who painted the Mona Lisa?', choices: ['Michelangelo', 'Leonardo da Vinci', 'Raphael', 'Donatello'], answer: 1 },
  { q: 'How many sides does a hexagon have?', choices: ['5', '6', '7', '8'], answer: 1 },
  { q: 'What is the hardest natural substance on Earth?', choices: ['Gold', 'Iron', 'Diamond', 'Quartz'], answer: 2 },
  { q: 'Which country is home to the kangaroo?', choices: ['Brazil', 'Australia', 'India', 'Kenya'], answer: 1 },
  { q: 'What is the smallest prime number?', choices: ['0', '1', '2', '3'], answer: 2 },
  { q: 'Which organ pumps blood through the body?', choices: ['Liver', 'Lungs', 'Heart', 'Kidney'], answer: 2 },
  { q: 'How many strings does a standard guitar have?', choices: ['4', '5', '6', '7'], answer: 2 },
  { q: 'What is the capital of Japan?', choices: ['Kyoto', 'Osaka', 'Tokyo', 'Seoul'], answer: 2 },
  { q: 'Which metal is liquid at room temperature?', choices: ['Mercury', 'Lead', 'Tin', 'Zinc'], answer: 0 },
  { q: 'What is the freezing point of water in Celsius?', choices: ['0', '32', '100', '-10'], answer: 0 },
  { q: 'Which animal is the largest living mammal?', choices: ['Elephant', 'Blue whale', 'Giraffe', 'Hippo'], answer: 1 },
  { q: 'How many minutes are in a full day?', choices: ['1200', '1440', '1600', '2400'], answer: 1 },
  { q: 'Which planet is known as the Red Planet?', choices: ['Venus', 'Mars', 'Mercury', 'Jupiter'], answer: 1 },
  { q: 'What is the main language spoken in Brazil?', choices: ['Spanish', 'Portuguese', 'French', 'English'], answer: 1 },
  { q: 'Which is the longest river in the world?', choices: ['Amazon', 'Nile', 'Yangtze', 'Mississippi'], answer: 1 },
  { q: 'How many colours are in a rainbow?', choices: ['5', '6', '7', '9'], answer: 2 },
  { q: 'What is the chemical symbol for water?', choices: ['CO2', 'H2O', 'O2', 'NaCl'], answer: 1 },
  { q: 'Which is the tallest mountain above sea level?', choices: ['K2', 'Kilimanjaro', 'Everest', 'Denali'], answer: 2 },
  { q: 'How many legs does a spider have?', choices: ['6', '8', '10', '12'], answer: 1 },
  { q: 'What is the largest planet-orbiting body of Earth called?', choices: ['The Sun', 'The Moon', 'Mars', 'Venus'], answer: 1 },
  { q: 'Which country built the Great Pyramid of Giza?', choices: ['Greece', 'Egypt', 'Italy', 'Mexico'], answer: 1 },
  { q: 'What do bees collect from flowers?', choices: ['Pollen', 'Sand', 'Water', 'Sap'], answer: 0 },
  { q: 'How many players are on a standard soccer team on the field?', choices: ['9', '10', '11', '12'], answer: 2 },
  { q: 'Which is a primary colour of light?', choices: ['Green', 'Orange', 'Purple', 'Brown'], answer: 0 },
  { q: 'What is the closest planet to the Sun?', choices: ['Venus', 'Earth', 'Mercury', 'Mars'], answer: 2 },
  { q: 'Which instrument has black and white keys?', choices: ['Violin', 'Piano', 'Flute', 'Drums'], answer: 1 },
  { q: 'How many degrees are in a right angle?', choices: ['45', '90', '180', '360'], answer: 1 },
  { q: 'What is the capital of Australia?', choices: ['Sydney', 'Melbourne', 'Canberra', 'Perth'], answer: 2 },
  { q: 'What is the capital of Canada?', choices: ['Toronto', 'Ottawa', 'Vancouver', 'Montreal'], answer: 1 },
  { q: 'Which country is the largest by land area?', choices: ['Canada', 'China', 'USA', 'Russia'], answer: 3 },
  { q: 'What is the chemical symbol for oxygen?', choices: ['Ox', 'O', 'Om', 'On'], answer: 1 },
  { q: 'Who wrote Romeo and Juliet?', choices: ['Charles Dickens', 'William Shakespeare', 'Mark Twain', 'Leo Tolstoy'], answer: 1 },
  { q: 'Which of these is a noble gas?', choices: ['Oxygen', 'Helium', 'Hydrogen', 'Nitrogen'], answer: 1 },
  { q: 'What is the chemical symbol for hydrogen?', choices: ['He', 'H', 'Hy', 'Hg'], answer: 1 },
  { q: 'Which is the smallest ocean?', choices: ['Indian', 'Arctic', 'Atlantic', 'Southern'], answer: 1 },
  { q: 'What is the fastest land animal?', choices: ['Lion', 'Cheetah', 'Horse', 'Pronghorn'], answer: 1 },
  { q: 'What is the currency of Japan?', choices: ['Won', 'Yuan', 'Yen', 'Ringgit'], answer: 2 },
  { q: 'How many degrees are in a circle?', choices: ['180', '270', '360', '90'], answer: 2 },
  { q: 'What is the longest bone in the human body?', choices: ['Femur', 'Tibia', 'Humerus', 'Spine'], answer: 0 },
  { q: 'Which vitamin does sunlight help the body produce?', choices: ['Vitamin A', 'Vitamin B12', 'Vitamin C', 'Vitamin D'], answer: 3 },
  { q: 'Which galaxy is Earth located in?', choices: ['Andromeda', 'Milky Way', 'Whirlpool', 'Sombrero'], answer: 1 },
  { q: 'The Great Barrier Reef is off the coast of which country?', choices: ['Brazil', 'Australia', 'Mexico', 'Thailand'], answer: 1 },
  { q: 'What is the tallest land animal?', choices: ['Elephant', 'Giraffe', 'Ostrich', 'Camel'], answer: 1 },
  { q: 'Which language has the most native speakers?', choices: ['English', 'Hindi', 'Mandarin Chinese', 'Spanish'], answer: 2 },
  { q: 'In which museum is the Mona Lisa displayed?', choices: ['The Louvre', 'The Met', 'Uffizi Gallery', 'Prado'], answer: 0 },
  { q: 'Who developed the theory of general relativity?', choices: ['Isaac Newton', 'Albert Einstein', 'Niels Bohr', 'Galileo'], answer: 1 },
  { q: 'Which sea creature has three hearts?', choices: ['Octopus', 'Shark', 'Tuna', 'Crab'], answer: 0 },
  { q: 'On which continent is the Sahara Desert?', choices: ['Asia', 'Africa', 'Australia', 'South America'], answer: 1 },
  { q: 'Which is the smallest planet in our solar system?', choices: ['Mercury', 'Mars', 'Venus', 'Earth'], answer: 0 },
  { q: 'Which country gifted the Statue of Liberty to the USA?', choices: ['United Kingdom', 'France', 'Spain', 'Italy'], answer: 1 },
  { q: 'Which gas makes up most of Earth\'s atmosphere?', choices: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Argon'], answer: 1 },
  { q: 'What is the largest organ of the human body?', choices: ['Skin', 'Liver', 'Brain', 'Heart'], answer: 0 },
  { q: 'What does the chemical symbol Na stand for?', choices: ['Sodium', 'Nitrogen', 'Nickel', 'Neon'], answer: 0 },
  { q: 'Which planet is famous for its prominent ring system?', choices: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'], answer: 1 },
  { q: 'Who is credited with the laws of motion and gravity?', choices: ['Einstein', 'Isaac Newton', 'Galileo', 'Tesla'], answer: 1 },
  { q: 'What is the fear of spiders called?', choices: ['Claustrophobia', 'Arachnophobia', 'Acrophobia', 'Agoraphobia'], answer: 1 },
  { q: 'What is the largest species of fish?', choices: ['Great white shark', 'Whale shark', 'Tiger shark', 'Manta ray'], answer: 1 },
  { q: 'In which country is the city of Istanbul?', choices: ['Greece', 'Turkey', 'Egypt', 'Iran'], answer: 1 },
  { q: 'Sound travels fastest through which medium?', choices: ['Air', 'Water', 'Steel', 'A vacuum'], answer: 2 },
  { q: 'Which planet rotates on its side?', choices: ['Mars', 'Uranus', 'Venus', 'Saturn'], answer: 1 },
  { q: 'Which part of the cell is called the powerhouse?', choices: ['Nucleus', 'Mitochondria', 'Ribosome', 'Membrane'], answer: 1 },
  { q: 'Which planet is known as Earth\'s twin in size?', choices: ['Mars', 'Venus', 'Mercury', 'Neptune'], answer: 1 },
  { q: 'Which ancient wonder of the world still stands today?', choices: ['Hanging Gardens', 'Great Pyramid of Giza', 'Colossus of Rhodes', 'Lighthouse of Alexandria'], answer: 1 },
  { q: 'What is the universal blood donor type?', choices: ['AB positive', 'O negative', 'A positive', 'B negative'], answer: 1 },
  { q: 'What is the currency of the United Kingdom?', choices: ['Euro', 'Pound sterling', 'Dollar', 'Franc'], answer: 1 },
  { q: 'How many chambers does the human heart have?', choices: ['2', '3', '4', '5'], answer: 2 },
  { q: 'Which is the deepest ocean?', choices: ['Atlantic', 'Indian', 'Pacific', 'Arctic'], answer: 2 },
  { q: 'What is the main ingredient in traditional guacamole?', choices: ['Avocado', 'Pea', 'Cucumber', 'Broccoli'], answer: 0 },
  { q: 'Which planet has the Great Red Spot?', choices: ['Mars', 'Jupiter', 'Saturn', 'Neptune'], answer: 1 },
  { q: 'Which gas do plants primarily absorb from the air during photosynthesis?', choices: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'], answer: 2 },
  { q: 'Approximately how many bones are in the adult human body?', choices: ['206', '320', '150', '98'], answer: 0 },
  { q: 'Which element has the highest electronegativity on the Pauling scale?', choices: ['Oxygen', 'Chlorine', 'Fluorine', 'Nitrogen'], answer: 2 },
  { q: 'What is the most abundant element in the universe?', choices: ['Helium', 'Oxygen', 'Carbon', 'Hydrogen'], answer: 3 },
  { q: 'How many hearts does an octopus have?', choices: ['One', 'Two', 'Three', 'Four'], answer: 2 },
  { q: 'What is the fastest land animal over short distances?', choices: ['Pronghorn antelope', 'Lion', 'Cheetah', 'Greyhound'], answer: 2 },
  { q: 'Diamond and graphite are both made entirely of which single element?', choices: ['Silicon', 'Carbon', 'Sulfur', 'Boron'], answer: 1 },
  { q: 'In a vacuum, sound travels at what speed?', choices: ['About 340 m/s', 'About 1,500 m/s', 'The speed of light', 'It cannot travel at all'], answer: 3 },
  { q: 'Which of these is NOT one of the four bases found in DNA?', choices: ['Adenine', 'Uracil', 'Guanine', 'Cytosine'], answer: 1 },
  { q: 'What metal-containing protein gives octopus blood its blue color?', choices: ['Hemoglobin', 'Hemocyanin', 'Myoglobin', 'Chlorophyll'], answer: 1 },
  { q: 'Which planet in our solar system has the most extensive ring system?', choices: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'], answer: 1 },
  { q: 'What is the powerhouse of the cell, where most ATP is produced?', choices: ['The nucleus', 'The ribosome', 'The mitochondrion', 'The Golgi apparatus'], answer: 2 },
  { q: 'Roughly what percentage of the air in Earth\'s atmosphere is nitrogen?', choices: ['About 21%', 'About 50%', 'About 78%', 'About 95%'], answer: 2 },
  { q: 'What is the pH of a perfectly neutral solution at 25 C?', choices: ['0', '7', '10', '14'], answer: 1 },
  { q: 'Which water bears (tiny animals) famously survived direct exposure to the vacuum of space?', choices: ['Tardigrades', 'Rotifers', 'Copepods', 'Nematodes'], answer: 0 },
  { q: 'What force keeps the planets in orbit around the Sun?', choices: ['Magnetism', 'Gravity', 'Electrostatic force', 'Nuclear force'], answer: 1 },
  { q: 'Why can honey found sealed in ancient Egyptian tombs still be edible?', choices: ['It was frozen', 'Its low water content and acidity prevent microbial growth', 'It was chemically embalmed', 'Bacteria cannot survive in darkness'], answer: 1 },
  { q: 'What part of the human eye controls how much light enters?', choices: ['The cornea', 'The retina', 'The iris', 'The lens'], answer: 2 },
  { q: 'Which subatomic particle carries a negative electric charge?', choices: ['Proton', 'Neutron', 'Electron', 'Photon'], answer: 2 },
  { q: 'What is the hardest known naturally occurring material?', choices: ['Quartz', 'Titanium', 'Diamond', 'Steel'], answer: 2 },
  { q: 'Which blood type is known as the universal donor for red blood cells?', choices: ['AB positive', 'O negative', 'A positive', 'B negative'], answer: 1 },
  { q: 'What gas do humans exhale as a waste product of cellular respiration?', choices: ['Oxygen', 'Carbon dioxide', 'Hydrogen', 'Helium'], answer: 1 },
  { q: 'What is the chemical formula for table salt?', choices: ['NaCl', 'KCl', 'CaCO3', 'NaHCO3'], answer: 0 },
  { q: 'Which branch of an animal\'s nervous system triggers the \'fight or flight\' response?', choices: ['Parasympathetic nervous system', 'Sympathetic nervous system', 'Somatic nervous system', 'Enteric nervous system'], answer: 1 },
  { q: 'Which scientist proposed the theory of evolution by natural selection?', choices: ['Gregor Mendel', 'Charles Darwin', 'Louis Pasteur', 'Isaac Newton'], answer: 1 },
  { q: 'Which process describes a solid turning directly into a gas without becoming liquid?', choices: ['Evaporation', 'Condensation', 'Sublimation', 'Melting'], answer: 2 },
  { q: 'What pigment makes most plant leaves appear green?', choices: ['Carotene', 'Melanin', 'Chlorophyll', 'Hemoglobin'], answer: 2 },
  { q: 'Which planet is the hottest in our solar system, due to its thick greenhouse atmosphere?', choices: ['Mercury', 'Venus', 'Mars', 'Jupiter'], answer: 1 },
  { q: 'Insects belong to which group of animals, characterized by an exoskeleton and jointed legs?', choices: ['Mollusks', 'Arthropods', 'Annelids', 'Cnidarians'], answer: 1 },
  { q: 'The Nile River flows into which body of water?', choices: ['Red Sea', 'Persian Gulf', 'Mediterranean Sea', 'Arabian Sea'], answer: 2 },
  { q: 'What is the highest mountain in Africa?', choices: ['Mount Kenya', 'Mount Kilimanjaro', 'Mount Stanley', 'Atlas Peak'], answer: 1 },
  { q: 'Which country has Canberra as its capital city?', choices: ['New Zealand', 'South Africa', 'Australia', 'Argentina'], answer: 2 },
  { q: 'Which is the smallest country in the world by land area?', choices: ['Monaco', 'Vatican City', 'San Marino', 'Nauru'], answer: 1 },
  { q: 'Nepal\'s national flag is unique because it is the only one that is not what shape?', choices: ['Triangular', 'Rectangular', 'Square', 'Circular'], answer: 1 },
  { q: 'Lake Titicaca, the world\'s highest navigable lake, lies on the border between Peru and which country?', choices: ['Chile', 'Ecuador', 'Bolivia', 'Colombia'], answer: 2 },
  { q: 'Angel Falls, the world\'s tallest uninterrupted waterfall, is located in which country?', choices: ['Brazil', 'Venezuela', 'Guyana', 'Peru'], answer: 1 },
  { q: 'The Caspian Sea is officially classified as the world\'s largest what?', choices: ['Bay', 'Lake', 'Gulf', 'Sea inlet'], answer: 1 },
  { q: 'The city of Istanbul straddles two continents. Which two?', choices: ['Africa and Asia', 'Europe and Africa', 'Europe and Asia', 'Asia and Australia'], answer: 2 },
  { q: 'Which river is the longest in South America?', choices: ['Orinoco River', 'Paraná River', 'Amazon River', 'São Francisco River'], answer: 2 },
  { q: 'Mount Everest sits on the border between Nepal and which country?', choices: ['India', 'China', 'Bhutan', 'Pakistan'], answer: 1 },
  { q: 'The Sahara, the world\'s largest hot desert, is located primarily on which continent?', choices: ['Asia', 'Africa', 'South America', 'Australia'], answer: 1 },
  { q: 'Which strait separates Spain from Morocco, linking the Atlantic Ocean and the Mediterranean Sea?', choices: ['Strait of Hormuz', 'Strait of Malacca', 'Strait of Gibraltar', 'Bering Strait'], answer: 2 },
  { q: 'What is the constitutional capital of Bolivia?', choices: ['La Paz', 'Sucre', 'Santa Cruz', 'Cochabamba'], answer: 1 },
  { q: 'Which country is both the largest in South America and the only one there where Portuguese is the official language?', choices: ['Argentina', 'Brazil', 'Colombia', 'Peru'], answer: 1 },
  { q: 'Mount Fuji, the highest mountain, is a famous landmark of which country?', choices: ['South Korea', 'China', 'Japan', 'Vietnam'], answer: 2 },
  { q: 'The Danube River flows through more countries than any other river. Into which sea does it empty?', choices: ['Baltic Sea', 'Black Sea', 'Adriatic Sea', 'Caspian Sea'], answer: 1 },
  { q: 'Which mountain range forms a natural border between France and Spain?', choices: ['The Alps', 'The Pyrenees', 'The Apennines', 'The Carpathians'], answer: 1 },
  { q: 'What is the capital of Egypt?', choices: ['Alexandria', 'Cairo', 'Giza', 'Luxor'], answer: 1 },
  { q: 'Greenland, the world\'s largest island, is an autonomous territory of which country?', choices: ['Norway', 'Iceland', 'Denmark', 'Canada'], answer: 2 },
  { q: 'The Andes, the world\'s longest continental mountain range, run along which continent?', choices: ['Africa', 'Asia', 'South America', 'Europe'], answer: 2 },
  { q: 'Which country\'s flag features a red maple leaf on a white square between two red bars?', choices: ['Lebanon', 'Canada', 'Switzerland', 'Peru'], answer: 1 },
  { q: 'What is the largest country in the world by total area?', choices: ['Canada', 'China', 'Russia', 'United States'], answer: 2 },
  { q: 'The Victoria Falls lie on the border between Zambia and which country?', choices: ['Botswana', 'Mozambique', 'Zimbabwe', 'Namibia'], answer: 2 },
  { q: 'Liechtenstein and Uzbekistan are the world\'s only two countries that are described as what?', choices: ['Microstates', 'Doubly landlocked', 'City-states', 'Equatorial'], answer: 1 },
  { q: 'The Volga, Europe\'s longest river, flows mostly through which country?', choices: ['Germany', 'Russia', 'Ukraine', 'Poland'], answer: 1 },
  { q: 'What is the capital of Turkey?', choices: ['Istanbul', 'Izmir', 'Ankara', 'Antalya'], answer: 2 },
  { q: 'Which sea, bordered by Israel and Jordan, is the lowest exposed point on Earth\'s land surface?', choices: ['Red Sea', 'Dead Sea', 'Aral Sea', 'Black Sea'], answer: 1 },
  { q: 'The Iberian Peninsula is mainly made up of Spain and which other country?', choices: ['France', 'Italy', 'Portugal', 'Morocco'], answer: 2 },
  { q: 'Which African country is entirely surrounded by South Africa?', choices: ['Eswatini', 'Lesotho', 'Botswana', 'Malawi'], answer: 1 },
  { q: 'The Panama Canal connects the Pacific Ocean to which other ocean?', choices: ['Indian Ocean', 'Arctic Ocean', 'Atlantic Ocean', 'Southern Ocean'], answer: 2 },
  { q: 'In Greek mythology, which hero killed the Minotaur in the Labyrinth on Crete with the help of Ariadne\'s thread?', choices: ['Heracles', 'Perseus', 'Theseus', 'Jason'], answer: 2 },
  { q: 'The Code of Hammurabi, one of the oldest known law codes, was issued by a king of which ancient empire?', choices: ['Egypt', 'Babylon', 'Persia', 'Assyria'], answer: 1 },
  { q: 'In Norse mythology, who guards the rainbow bridge Bifrost and is said to sound a horn at the onset of Ragnarok?', choices: ['Loki', 'Heimdall', 'Tyr', 'Baldr'], answer: 1 },
  { q: 'The Rosetta Stone, key to deciphering Egyptian hieroglyphs, carries the same decree in how many distinct scripts?', choices: ['Two', 'Three', 'Four', 'Five'], answer: 1 },
  { q: 'In Hinduism\'s Trimurti, which god is traditionally described as the destroyer?', choices: ['Brahma', 'Vishnu', 'Shiva', 'Ganesha'], answer: 2 },
  { q: 'How many Pillars of Islam are there?', choices: ['Three', 'Four', 'Five', 'Seven'], answer: 2 },
  { q: 'In Egyptian mythology, which jackal-headed god is associated with mummification and the afterlife?', choices: ['Horus', 'Anubis', 'Set', 'Thoth'], answer: 1 },
  { q: 'Rosa Parks\'s refusal to give up her bus seat in 1955 sparked a boycott in which U.S. city?', choices: ['Birmingham', 'Selma', 'Montgomery', 'Atlanta'], answer: 2 },
  { q: 'Magna Carta, agreed to by an English king at Runnymede in 1215, bears the name of which monarch?', choices: ['Richard I', 'King John', 'Henry II', 'Edward I'], answer: 1 },
  { q: 'The Roman god Janus, depicted with two faces, lends his name to which month of the year?', choices: ['January', 'June', 'March', 'August'], answer: 0 },
  { q: 'In Judaism, the Torah consists of how many books, also called the Five Books of Moses?', choices: ['Three', 'Five', 'Seven', 'Ten'], answer: 1 },
  { q: 'China\'s famous Terracotta Army was buried to guard the tomb of which ruler, the first emperor of a unified China?', choices: ['Kublai Khan', 'Qin Shi Huang', 'Emperor Wu of Han', 'Sun Yat-sen'], answer: 1 },
  { q: 'In Greek myth, after Pandora opened the jar releasing evils into the world, what single thing was said to remain inside?', choices: ['Hope', 'Wisdom', 'Fire', 'Love'], answer: 0 },
  { q: 'Who is traditionally regarded as the founder of Sikhism?', choices: ['Guru Gobind Singh', 'Guru Nanak', 'Guru Arjan', 'Guru Tegh Bahadur'], answer: 1 },
  { q: 'In Aztec mythology, Quetzalcoatl is depicted as what kind of creature?', choices: ['A winged lion', 'A feathered serpent', 'A jaguar warrior', 'A two-headed eagle'], answer: 1 },
  { q: 'The Berlin Wall, a Cold War symbol, fell in which year?', choices: ['1985', '1987', '1989', '1991'], answer: 2 },
  { q: 'Johannes Gutenberg is credited with introducing movable-type printing to Europe and printing a famous edition of which book?', choices: ['The Quran', 'The Bible', 'Euclid\'s Elements', 'The Odyssey'], answer: 1 },
  { q: 'In Norse mythology, the thunder god Thor wields what named weapon?', choices: ['Gungnir', 'Mjolnir', 'Gram', 'Laevateinn'], answer: 1 },
  { q: 'Martin Luther\'s Ninety-Five Theses, which helped spark the Protestant Reformation, were posted in which town in 1517?', choices: ['Geneva', 'Wittenberg', 'Worms', 'Mainz'], answer: 1 },
  { q: 'The intact tomb of which Egyptian pharaoh was discovered by Howard Carter in 1922?', choices: ['Ramesses II', 'Tutankhamun', 'Akhenaten', 'Thutmose III'], answer: 1 },
  { q: 'In Greek mythology, who is the king of the gods who rules from Mount Olympus?', choices: ['Poseidon', 'Hades', 'Zeus', 'Apollo'], answer: 2 },
  { q: 'The first sustained powered airplane flight, by the Wright brothers in 1903, took place near which location?', choices: ['Dayton, Ohio', 'Kitty Hawk, North Carolina', 'Roswell, New Mexico', 'Cape Canaveral, Florida'], answer: 1 },
  { q: 'The Hindu sacred text known as the Bhagavad Gita is set within which larger epic?', choices: ['The Ramayana', 'The Mahabharata', 'The Vedas', 'The Puranas'], answer: 1 },
  { q: 'In Buddhism, how many spokes does the traditional Dharmachakra wheel most commonly have, matching the Noble Eightfold Path?', choices: ['Four', 'Six', 'Eight', 'Twelve'], answer: 2 },
  { q: 'For Muslims, the direction of prayer (qibla) points toward the Kaaba in which city?', choices: ['Medina', 'Jerusalem', 'Mecca', 'Baghdad'], answer: 2 },
  { q: 'Which structure is the only one of the Seven Wonders of the Ancient World that still survives largely intact?', choices: ['The Colossus of Rhodes', 'The Great Pyramid of Giza', 'The Hanging Gardens of Babylon', 'The Lighthouse of Alexandria'], answer: 1 },
  { q: 'In Roman mythology, the god Mars was said to be the father of which legendary founders of Rome?', choices: ['Aeneas and Dido', 'Romulus and Remus', 'Castor and Pollux', 'Numa and Tullus'], answer: 1 },
  { q: 'The collection of sayings known as the Analects records the teachings of which Chinese thinker?', choices: ['Laozi', 'Confucius', 'Mencius', 'Sun Tzu'], answer: 1 },
  { q: 'The Dead Sea Scrolls, ancient mostly-Hebrew manuscripts, were first discovered in caves near which site beginning in 1947?', choices: ['Masada', 'Qumran', 'Jericho', 'Petra'], answer: 1 },
  { q: 'In Greek mythology, the warrior Achilles had a single point of vulnerability located where on his body?', choices: ['His heel', 'His chest', 'His left eye', 'His wrist'], answer: 0 },
  { q: 'Julius Caesar was assassinated by Roman senators in 44 BC on which date, famously called the Ides of March?', choices: ['March 1', 'March 15', 'March 21', 'March 31'], answer: 1 },
  { q: 'The storming of the Bastille, a key event of the French Revolution, occurred on July 14 of which year?', choices: ['1776', '1789', '1799', '1804'], answer: 1 },
  { q: 'In Buddhism, Siddhartha Gautama is said to have attained enlightenment while meditating beneath what kind of tree?', choices: ['An olive tree', 'A Bodhi tree', 'A banyan tree', 'A cedar tree'], answer: 1 },
  { q: 'Which artist painted \'The Starry Night\'?', choices: ['Claude Monet', 'Pablo Picasso', 'Vincent van Gogh', 'Salvador Dalí'], answer: 2 },
  { q: 'In which Italian city is Shakespeare\'s \'Romeo and Juliet\' primarily set?', choices: ['Venice', 'Verona', 'Florence', 'Milan'], answer: 1 },
  { q: 'How many keys does a standard modern piano have?', choices: ['76', '88', '61', '96'], answer: 1 },
  { q: 'Which country won the very first FIFA World Cup in 1930?', choices: ['Brazil', 'Italy', 'Uruguay', 'Argentina'], answer: 2 },
  { q: 'Who wrote the novella \'The Old Man and the Sea\'?', choices: ['F. Scott Fitzgerald', 'Ernest Hemingway', 'John Steinbeck', 'William Faulkner'], answer: 1 },
  { q: 'How many strings does a standard violin have?', choices: ['Six', 'Four', 'Five', 'Seven'], answer: 1 },
  { q: 'How many players from one team are on a basketball court at the same time?', choices: ['Six', 'Five', 'Seven', 'Four'], answer: 1 },
  { q: 'Beethoven\'s choral Symphony No. 9 famously sets which poem to music in its finale?', choices: ['Ode to a Nightingale', 'The Raven', 'Ode to Joy', 'Paradise Lost'], answer: 2 },
  { q: 'Which British author wrote \'Charlie and the Chocolate Factory\'?', choices: ['C. S. Lewis', 'Roald Dahl', 'J. M. Barrie', 'Beatrix Potter'], answer: 1 },
  { q: 'In music notation, how many beats does a whole note (semibreve) typically last in 4/4 time?', choices: ['One', 'Two', 'Four', 'Eight'], answer: 2 },
  { q: 'Which sport uses terms such as \'love\', \'deuce\', and \'ace\'?', choices: ['Cricket', 'Tennis', 'Golf', 'Squash'], answer: 1 },
  { q: 'Who composed the opera \'The Magic Flute\'?', choices: ['Giuseppe Verdi', 'Richard Wagner', 'Wolfgang Amadeus Mozart', 'Johann Sebastian Bach'], answer: 2 },
  { q: 'What is the term for a word that reads the same forwards and backwards, like \'level\'?', choices: ['Homonym', 'Palindrome', 'Anagram', 'Synonym'], answer: 1 },
  { q: 'Which Russian author wrote the novel \'War and Peace\'?', choices: ['Fyodor Dostoevsky', 'Leo Tolstoy', 'Anton Chekhov', 'Ivan Turgenev'], answer: 1 },
  { q: 'In a standard orchestra, which instrument family does the trumpet belong to?', choices: ['Woodwind', 'Strings', 'Brass', 'Percussion'], answer: 2 },
  { q: 'What is the maximum break a player can score in a single frame of snooker (no fouls)?', choices: ['100', '147', '180', '155'], answer: 1 },
  { q: 'Which playwright wrote \'Hamlet\', \'Macbeth\', and \'King Lear\'?', choices: ['Christopher Marlowe', 'Ben Jonson', 'William Shakespeare', 'Oscar Wilde'], answer: 2 },
  { q: 'What does the musical term \'forte\' instruct a performer to do?', choices: ['Play softly', 'Play loudly', 'Play faster', 'Play slower'], answer: 1 },
  { q: 'In which country did the Olympic Games originate in antiquity?', choices: ['Egypt', 'Italy', 'Greece', 'Persia'], answer: 2 },
  { q: 'Who painted the ceiling of the Sistine Chapel?', choices: ['Raphael', 'Michelangelo', 'Donatello', 'Botticelli'], answer: 1 },
  { q: 'What is a group of lions properly called?', choices: ['A herd', 'A pack', 'A pride', 'A flock'], answer: 2 },
  { q: 'Which novel by George Orwell features the slogan \'Big Brother is watching you\'?', choices: ['Animal Farm', 'Brave New World', 'Nineteen Eighty-Four', 'Fahrenheit 451'], answer: 2 },
  { q: 'In golf, what term describes a score of two strokes under par on a single hole?', choices: ['Birdie', 'Bogey', 'Eagle', 'Albatross'], answer: 2 },
  { q: 'Which Italian word, meaning \'fresh\', describes a painting technique done on wet plaster?', choices: ['Tempera', 'Fresco', 'Gouache', 'Impasto'], answer: 1 },
  { q: 'How many lines does a traditional sonnet have?', choices: ['Twelve', 'Fourteen', 'Sixteen', 'Ten'], answer: 1 },
  { q: 'Which woodwind instrument is the largest and lowest-pitched member commonly found in an orchestra\'s double-reed section?', choices: ['Oboe', 'Clarinet', 'Bassoon', 'Flute'], answer: 2 },
  { q: 'In which sport would you perform a \'slam dunk\'?', choices: ['Volleyball', 'Basketball', 'Handball', 'Water polo'], answer: 1 },
  { q: 'Who wrote the epic poems \'The Iliad\' and \'The Odyssey\'?', choices: ['Virgil', 'Homer', 'Sophocles', 'Ovid'], answer: 1 },
  { q: 'What is the standard number of squares along one edge of a chessboard?', choices: ['Six', 'Eight', 'Ten', 'Twelve'], answer: 1 },
  { q: 'The primary colours of light (additive colour) are red, green, and which third colour?', choices: ['Yellow', 'Blue', 'Cyan', 'Magenta'], answer: 1 },
];

// ---- Quantities: { label, value, unit }. Used by Higher/Lower & Rank It — correct
// RELATIVE order is what matters; values are canonical approximations. ----
export const QUANTITIES = [
  { label: 'Speed of a cheetah (top)', value: 110, unit: 'km/h' },
  { label: 'Speed of a house cat (top)', value: 48, unit: 'km/h' },
  { label: 'Speed of a human sprinter (top)', value: 44, unit: 'km/h' },
  { label: 'Speed of a garden snail', value: 0.05, unit: 'km/h' },
  { label: 'Speed of a peregrine falcon (dive)', value: 320, unit: 'km/h' },
  { label: 'Diameter of Earth', value: 12742, unit: 'km' },
  { label: 'Diameter of the Moon', value: 3474, unit: 'km' },
  { label: 'Diameter of Jupiter', value: 139820, unit: 'km' },
  { label: 'Diameter of Mars', value: 6779, unit: 'km' },
  { label: 'Height of Mount Everest', value: 8849, unit: 'm' },
  { label: 'Height of the Eiffel Tower', value: 330, unit: 'm' },
  { label: 'Height of the Burj Khalifa', value: 828, unit: 'm' },
  { label: 'Height of the Statue of Liberty', value: 93, unit: 'm' },
  { label: 'Number of bones in the human body', value: 206, unit: 'bones' },
  { label: 'Number of teeth in an adult human', value: 32, unit: 'teeth' },
  { label: 'Legs on a spider', value: 8, unit: 'legs' },
  { label: 'Legs on an insect', value: 6, unit: 'legs' },
  { label: 'Days in a leap year', value: 366, unit: 'days' },
  { label: 'Boiling point of water', value: 100, unit: '°C' },
  { label: 'Number of keys on a standard piano', value: 88, unit: 'keys' },
  { label: 'Number of squares on a chessboard', value: 64, unit: 'squares' },
  { label: 'Cards in a standard deck', value: 52, unit: 'cards' },
  { label: 'Players on a basketball team (on court)', value: 5, unit: 'players' },
  { label: 'Wonders of the ancient world', value: 7, unit: 'wonders' },
  { label: 'Strings on a violin', value: 4, unit: 'strings' },
  { label: 'Length of a marathon', value: 42, unit: 'km' },
  { label: 'Number of moons of Mars', value: 2, unit: 'moons' },
  { label: 'Number of planets in the solar system', value: 8, unit: 'planets' },
  { label: 'Speed of sound in air', value: 1235, unit: 'km/h' },
  { label: 'Cruising speed of a passenger jet', value: 900, unit: 'km/h' },
  { label: 'Speed of a three-toed sloth', value: 0.24, unit: 'km/h' },
  { label: 'Average human walking speed', value: 5, unit: 'km/h' },
  { label: 'Distance from the Earth to the Moon', value: 384400, unit: 'km' },
  { label: 'Diameter of the Sun', value: 1391000, unit: 'km' },
  { label: 'Diameter of Venus', value: 12104, unit: 'km' },
  { label: 'Diameter of Mercury', value: 4879, unit: 'km' },
  { label: 'Height of the CN Tower', value: 553, unit: 'm' },
  { label: 'Height of the Great Pyramid of Giza', value: 139, unit: 'm' },
  { label: 'Number of US states', value: 50, unit: 'states' },
  { label: 'Letters in the English alphabet', value: 26, unit: 'letters' },
  { label: 'Holes on a standard golf course', value: 18, unit: 'holes' },
  { label: 'Weeks in a year', value: 52, unit: 'weeks' },
  { label: 'Hours in a week', value: 168, unit: 'hours' },
  { label: 'Bones a human is born with', value: 270, unit: 'bones' },
  { label: 'Countries in Africa', value: 54, unit: 'countries' },
  { label: 'Chromosomes in a human cell', value: 46, unit: 'chromosomes' },
  { label: 'Elements in the periodic table', value: 118, unit: 'elements' },
  { label: 'Players on an American football team (on field)', value: 11, unit: 'players' },
  { label: 'Length of the Great Wall of China', value: 21196, unit: 'km' },
  { label: 'Speed of light in a vacuum', value: 299792, unit: 'km/s' },
  { label: 'Average distance from Earth to the Moon', value: 384400, unit: 'km' },
  { label: 'Average distance from Earth to the Sun (1 AU)', value: 150, unit: 'million km' },
  { label: 'International Space Station orbital speed', value: 28000, unit: 'km/h' },
  { label: 'International Space Station orbital altitude', value: 400, unit: 'km' },
  { label: 'Speed of sound in dry air at sea level', value: 343, unit: 'm/s' },
  { label: 'Earth\'s orbital speed around the Sun', value: 30, unit: 'km/s' },
  { label: 'Height of Mount Everest above sea level', value: 8849, unit: 'm' },
  { label: 'Depth of the Challenger Deep (Mariana Trench)', value: 10935, unit: 'm' },
  { label: 'Height of Angel Falls (world\'s tallest waterfall)', value: 979, unit: 'm' },
  { label: 'Height of the Burj Khalifa (tallest building)', value: 828, unit: 'm' },
  { label: 'Length of the Nile River', value: 6650, unit: 'km' },
  { label: 'Area of the Sahara Desert', value: 9200000, unit: 'sq km' },
  { label: 'Peregrine falcon top diving speed', value: 320, unit: 'km/h' },
  { label: 'Top speed of a cheetah (sprint)', value: 110, unit: 'km/h' },
  { label: 'Length of an adult blue whale', value: 30, unit: 'm' },
  { label: 'Height of an adult giraffe', value: 5, unit: 'm' },
  { label: 'Wingspan of a wandering albatross', value: 3, unit: 'm' },
  { label: 'Boiling point of water at sea level', value: 100, unit: '°C' },
  { label: 'Freezing point of water', value: 0, unit: '°C' },
  { label: 'Absolute zero', value: -273, unit: '°C' },
  { label: 'Earth\'s gravitational acceleration', value: 9.8, unit: 'm/s²' },
  { label: 'Average thickness of Earth\'s atmosphere (Karman line, edge of space)', value: 100, unit: 'km' },
  { label: 'Circumference of the Earth (equator)', value: 40075, unit: 'km' },
  { label: 'Average human body temperature', value: 37, unit: '°C' },
  { label: 'Speed of a commercial jet airliner (cruising)', value: 900, unit: 'km/h' },
  { label: 'Terminal velocity of a human skydiver (belly-down)', value: 195, unit: 'km/h' },
  { label: 'Surface temperature of the Sun', value: 5500, unit: '°C' },
  { label: 'Diameter of a human hair (average)', value: 75, unit: 'micrometers' },
  { label: 'Width of the Milky Way galaxy', value: 100000, unit: 'light-years' },
  { label: 'Number of days for light from the Sun to reach Earth', value: 8, unit: 'minutes' },
  { label: 'Bones in the adult human body', value: 206, unit: 'bones' },
  { label: 'Permanent teeth in a full adult set', value: 32, unit: 'teeth' },
  { label: 'Pairs of ribs in the human body', value: 12, unit: 'pairs' },
  { label: 'Chambers in the human heart', value: 4, unit: 'chambers' },
  { label: 'Resting adult heart rate (typical)', value: 70, unit: 'beats/min' },
  { label: 'Vertebrae in the human spine', value: 33, unit: 'vertebrae' },
  { label: 'Pairs of cranial nerves', value: 12, unit: 'pairs' },
  { label: 'Adult human blood volume (typical)', value: 5, unit: 'litres' },
  { label: 'Cervical (neck) vertebrae in humans', value: 7, unit: 'vertebrae' },
  { label: 'Height of a basketball hoop rim', value: 305, unit: 'cm' },
  { label: 'Official marathon distance', value: 42.195, unit: 'km' },
  { label: 'Tennis net height at the centre', value: 91.4, unit: 'cm' },
  { label: 'Regulation soccer match duration', value: 90, unit: 'minutes' },
  { label: 'Diameter of a regulation golf hole', value: 108, unit: 'mm' },
  { label: 'Players on a soccer team on the field', value: 11, unit: 'players' },
  { label: 'Points for a touchdown in American football', value: 6, unit: 'points' },
  { label: 'Squares on one side of a chessboard', value: 8, unit: 'squares' },
  { label: 'Lanes in an Olympic swimming pool', value: 8, unit: 'lanes' },
  { label: 'Keys on a standard piano', value: 88, unit: 'keys' },
  { label: 'Concert pitch of the note A above middle C', value: 440, unit: 'Hz' },
  { label: 'Strings on a standard guitar', value: 6, unit: 'strings' },
  { label: 'Notes in a chromatic musical octave', value: 12, unit: 'notes' },
  { label: 'Strings on a standard violin', value: 4, unit: 'strings' },
  { label: 'Beats per bar in 4/4 time', value: 4, unit: 'beats' },
  { label: 'Seconds in a full day', value: 86400, unit: 'seconds' },
  { label: 'Minutes in a week', value: 10080, unit: 'minutes' },
  { label: 'Degrees the hour hand moves per hour', value: 30, unit: 'degrees' },
  { label: 'Cards in a standard playing deck', value: 52, unit: 'cards' },
  { label: 'Standard dimples on a golf ball (common)', value: 336, unit: 'dimples' },
  { label: 'Squares on a standard Monopoly board', value: 40, unit: 'squares' },
  { label: 'Pips (dots) on a six-sided die', value: 21, unit: 'pips' },
];

// ---- Numeric facts: { prompt, answer, unit }. Used by Price Is Wrong (closest-without-over)
// and Guesstimate (log-closeness). Stable physical quantities, not market prices. ----
export const NUMERIC_FACTS = [
  { prompt: 'Height of the Eiffel Tower', answer: 330, unit: 'metres' },
  { prompt: 'Number of bones in the adult human body', answer: 206, unit: 'bones' },
  { prompt: 'Boiling point of water', answer: 100, unit: '°C' },
  { prompt: 'Number of keys on a standard piano', answer: 88, unit: 'keys' },
  { prompt: 'Length of a marathon (rounded)', answer: 42, unit: 'km' },
  { prompt: 'Number of squares on a chessboard', answer: 64, unit: 'squares' },
  { prompt: 'Height of Mount Everest', answer: 8849, unit: 'metres' },
  { prompt: 'Number of countries in the United Nations', answer: 193, unit: 'countries' },
  { prompt: 'Number of hearts an octopus has', answer: 3, unit: 'hearts' },
  { prompt: 'Diameter of Earth', answer: 12742, unit: 'km' },
  { prompt: 'Number of teeth in an adult human', answer: 32, unit: 'teeth' },
  { prompt: 'Days it takes the Moon to orbit Earth (rounded)', answer: 27, unit: 'days' },
  { prompt: 'Height of the Burj Khalifa', answer: 828, unit: 'metres' },
  { prompt: 'Number of strings on a standard guitar', answer: 6, unit: 'strings' },
  { prompt: 'Speed of light (rounded)', answer: 300000, unit: 'km/s' },
  { prompt: 'Number of players on a soccer team on the field', answer: 11, unit: 'players' },
  { prompt: 'Number of minutes in a day', answer: 1440, unit: 'minutes' },
  { prompt: 'Freezing point of water in Fahrenheit', answer: 32, unit: '°F' },
  { prompt: 'Number of US states', answer: 50, unit: 'states' },
  { prompt: 'Number of bones a human is born with', answer: 270, unit: 'bones' },
  { prompt: 'Number of chromosomes in a human cell', answer: 46, unit: 'chromosomes' },
  { prompt: 'Number of countries in Africa', answer: 54, unit: 'countries' },
  { prompt: 'Number of elements in the periodic table', answer: 118, unit: 'elements' },
  { prompt: 'Distance from the Earth to the Moon', answer: 384400, unit: 'km' },
  { prompt: 'Diameter of the Sun', answer: 1391000, unit: 'km' },
  { prompt: 'Boiling point of water in Fahrenheit', answer: 212, unit: '°F' },
  { prompt: 'Number of seconds in an hour', answer: 3600, unit: 'seconds' },
  { prompt: 'Number of minutes in a week', answer: 10080, unit: 'minutes' },
  { prompt: 'Average human body temperature', answer: 37, unit: '°C' },
  { prompt: 'Number of vertebrae in the human spine', answer: 33, unit: 'vertebrae' },
  { prompt: 'Number of ribs in the human body', answer: 24, unit: 'ribs' },
  { prompt: 'Atomic number of carbon', answer: 6, unit: 'protons' },
  { prompt: 'Number of stars on the United States flag', answer: 50, unit: 'stars' },
  { prompt: 'Number of stripes on the United States flag', answer: 13, unit: 'stripes' },
  { prompt: 'Height of the CN Tower', answer: 553, unit: 'metres' },
  { prompt: 'Number of legs on a lobster', answer: 10, unit: 'legs' },
  { prompt: 'Number of players on a baseball team on the field', answer: 9, unit: 'players' },
  { prompt: 'Number of time zones in the world', answer: 24, unit: 'time zones' },
  { prompt: 'Speed of sound in air', answer: 343, unit: 'm/s' },
  { prompt: 'Number of weeks in a year', answer: 52, unit: 'weeks' },
  { prompt: 'Number of teeth in a full adult human set (including wisdom teeth)', answer: 32, unit: 'teeth' },
  { prompt: 'Number of baby (deciduous) teeth a child has', answer: 20, unit: 'teeth' },
  { prompt: 'Number of pairs of chromosomes in a human cell', answer: 23, unit: 'pairs' },
  { prompt: 'Number of pairs of ribs in a typical human', answer: 12, unit: 'pairs' },
  { prompt: 'Number of chambers in a human heart', answer: 4, unit: 'chambers' },
  { prompt: 'Number of legs on a spider', answer: 8, unit: 'legs' },
  { prompt: 'Number of legs on an insect', answer: 6, unit: 'legs' },
  { prompt: 'Number of neck (cervical) vertebrae in a giraffe', answer: 7, unit: 'vertebrae' },
  { prompt: 'Number of stomach compartments in a cow', answer: 4, unit: 'compartments' },
  { prompt: 'Number of eyes a typical adult bee has (compound plus simple)', answer: 5, unit: 'eyes' },
  { prompt: 'Speed of light in a vacuum', answer: 299792458, unit: 'meters per second' },
  { prompt: 'Number of planets in our solar system', answer: 8, unit: 'planets' },
  { prompt: 'Number of moons orbiting Mars', answer: 2, unit: 'moons' },
  { prompt: 'Number of moons orbiting Earth', answer: 1, unit: 'moon' },
  { prompt: 'Approximate axial tilt of the Earth', answer: 23.4, unit: 'degrees' },
  { prompt: 'Number of degrees of longitude between adjacent standard time zones', answer: 15, unit: 'degrees' },
  { prompt: 'Number of Earth days it takes the Moon to complete one orbit (sidereal month, rounded)', answer: 27, unit: 'days' },
  { prompt: 'Approximate number of minutes sunlight takes to travel from the Sun to Earth', answer: 8, unit: 'minutes' },
  { prompt: 'Number of constellations officially recognized by the International Astronomical Union', answer: 88, unit: 'constellations' },
  { prompt: 'Boiling point of water at standard atmospheric pressure', answer: 100, unit: 'degrees Celsius' },
  { prompt: 'pH of pure water at room temperature (neutral)', answer: 7, unit: 'pH' },
  { prompt: 'Atomic number of gold', answer: 79, unit: 'protons' },
  { prompt: 'Atomic number of iron', answer: 26, unit: 'protons' },
  { prompt: 'Atomic number of oxygen', answer: 8, unit: 'protons' },
  { prompt: 'Number of protons in a hydrogen atom', answer: 1, unit: 'proton' },
  { prompt: 'Hardness of diamond on the Mohs scale', answer: 10, unit: 'out of 10' },
  { prompt: 'Number of naturally occurring noble gases', answer: 6, unit: 'noble gases' },
  { prompt: 'Approximate percentage of Earth\'s atmosphere that is nitrogen', answer: 78, unit: 'percent' },
  { prompt: 'Approximate percentage of Earth\'s surface covered by water', answer: 71, unit: 'percent' },
  { prompt: 'Number of bones in one human hand (including the wrist)', answer: 27, unit: 'bones' },
  { prompt: 'Number of cervical (neck) vertebrae in a human', answer: 7, unit: 'vertebrae' },
  { prompt: 'Number of bones fused together to form the adult human skull', answer: 22, unit: 'bones' },
  { prompt: 'Number of continents on Earth', answer: 7, unit: 'continents' },
  { prompt: 'Number of countries on the continent of Africa (UN members)', answer: 54, unit: 'countries' },
  { prompt: 'Number of Canadian provinces', answer: 10, unit: 'provinces' },
  { prompt: 'Number of the Great Lakes of North America', answer: 5, unit: 'lakes' },
  { prompt: 'Number of standard time zones the world is divided into', answer: 24, unit: 'time zones' },
  { prompt: 'Number of cardinal directions on a compass (N, E, S, W)', answer: 4, unit: 'directions' },
  { prompt: 'Number of degrees in a full circle', answer: 360, unit: 'degrees' },
  { prompt: 'Number of players per team on the field in association football (soccer)', answer: 11, unit: 'players' },
  { prompt: 'Number of players per team on the court in indoor volleyball', answer: 6, unit: 'players' },
  { prompt: 'Number of players per team on the court in basketball', answer: 5, unit: 'players' },
  { prompt: 'Number of players in a standard baseball lineup on the field', answer: 9, unit: 'players' },
  { prompt: 'Number of holes on a standard round of golf', answer: 18, unit: 'holes' },
  { prompt: 'Number of pins set up in ten-pin bowling', answer: 10, unit: 'pins' },
  { prompt: 'Number of interlocking rings on the Olympic flag', answer: 5, unit: 'rings' },
  { prompt: 'Number of innings in a regulation baseball game', answer: 9, unit: 'innings' },
  { prompt: 'Length of a tennis court from baseline to baseline', answer: 78, unit: 'feet' },
  { prompt: 'Official distance of a marathon', answer: 42.195, unit: 'kilometres' },
  { prompt: 'Number of letters in the modern English alphabet', answer: 26, unit: 'letters' },
  { prompt: 'Number of letters in the Greek alphabet', answer: 24, unit: 'letters' },
  { prompt: 'Number of vowels in the modern English alphabet (A, E, I, O, U)', answer: 5, unit: 'vowels' },
  { prompt: 'Number of squares on a standard chessboard', answer: 64, unit: 'squares' },
  { prompt: 'Number of pawns each player starts with in chess', answer: 8, unit: 'pawns' },
  { prompt: 'Number of keys on a standard full-size piano', answer: 88, unit: 'keys' },
  { prompt: 'Number of spaces around the edge of a standard Monopoly board', answer: 40, unit: 'spaces' },
];

// ---- Timeline events: { event, year }. Well-known, uncontroversial dates. ----
export const EVENTS = [
  { event: 'First human steps on the Moon', year: 1969 },
  { event: 'The Berlin Wall falls', year: 1989 },
  { event: 'The Titanic sinks', year: 1912 },
  { event: 'End of World War II', year: 1945 },
  { event: 'The first iPhone is released', year: 2007 },
  { event: 'The World Wide Web is invented', year: 1989 },
  { event: 'Declaration of US Independence', year: 1776 },
  { event: 'The French Revolution begins', year: 1789 },
  { event: 'The first powered airplane flight (Wright brothers)', year: 1903 },
  { event: 'The first successful printing press (Gutenberg)', year: 1440 },
  { event: 'Columbus reaches the Americas', year: 1492 },
  { event: 'The Great Fire of London', year: 1666 },
  { event: 'The first modern Olympic Games', year: 1896 },
  { event: 'The discovery of penicillin', year: 1928 },
  { event: 'The fall of the Roman Empire (Western)', year: 476 },
  { event: 'The signing of the Magna Carta', year: 1215 },
  { event: 'The first email is sent', year: 1971 },
  { event: 'The first photograph is taken', year: 1826 },
  { event: 'World War I begins', year: 1914 },
  { event: 'The American Civil War begins', year: 1861 },
  { event: 'Sputnik, the first artificial satellite, is launched', year: 1957 },
  { event: 'The fall of Constantinople', year: 1453 },
  { event: 'The United States Constitution is signed', year: 1787 },
  { event: 'Alexander Graham Bell patents the telephone', year: 1876 },
  { event: 'The first human heart transplant', year: 1967 },
  { event: 'The Chernobyl nuclear disaster', year: 1986 },
  { event: 'The Hubble Space Telescope is launched', year: 1990 },
  { event: 'Nelson Mandela becomes President of South Africa', year: 1994 },
  { event: 'The Spanish Armada is defeated', year: 1588 },
  { event: 'Watson and Crick describe the structure of DNA', year: 1953 },
  { event: 'Mount Vesuvius destroys Pompeii', year: 79 },
  { event: 'The Battle of Hastings', year: 1066 },
  { event: 'Yuri Gagarin becomes the first human in space', year: 1961 },
  { event: 'Abraham Lincoln is assassinated', year: 1865 },
  { event: 'The first Star Wars film is released', year: 1977 },
  { event: 'The Soviet Union dissolves', year: 1991 },
  { event: 'Wikipedia is launched', year: 2001 },
  { event: 'The Wall Street Crash triggers the Great Depression', year: 1929 },
  { event: 'The Eiffel Tower is completed', year: 1889 },
  { event: 'The Panama Canal opens', year: 1914 },
  { event: 'The Black Death reaches Europe', year: 1347 },
  { event: 'Traditional founding of the city of Rome', year: -753 },
  { event: 'First recorded ancient Olympic Games held at Olympia', year: -776 },
  { event: 'Founding of the Roman Republic after the last king is overthrown', year: -509 },
  { event: 'Death of Alexander the Great in Babylon', year: -323 },
  { event: 'Julius Caesar assassinated on the Ides of March', year: -44 },
  { event: 'Roman Emperor Constantine issues the Edict of Milan tolerating Christianity', year: 313 },
  { event: 'Charlemagne crowned Holy Roman Emperor in Rome', year: 800 },
  { event: 'Pope Urban II calls the First Crusade at the Council of Clermont', year: 1095 },
  { event: 'Marco Polo sets out on his journey toward China', year: 1271 },
  { event: 'Gutenberg completes his printing of the Bible with movable type', year: 1455 },
  { event: 'Vasco da Gama reaches India by sea, rounding Africa', year: 1498 },
  { event: 'Martin Luther posts his Ninety-Five Theses', year: 1517 },
  { event: 'Magellan\'s expedition completes the first circumnavigation of the globe', year: 1522 },
  { event: 'Copernicus publishes his heliocentric model of the universe', year: 1543 },
  { event: 'Galileo first uses a telescope to observe the night sky', year: 1609 },
  { event: 'The Pilgrims arrive in North America aboard the Mayflower', year: 1620 },
  { event: 'Isaac Newton publishes the Principia, founding classical mechanics', year: 1687 },
  { event: 'The Boston Tea Party protest in colonial Massachusetts', year: 1773 },
  { event: 'Edward Jenner performs the first smallpox vaccination', year: 1796 },
  { event: 'The Rosetta Stone is discovered during Napoleon\'s Egyptian campaign', year: 1799 },
  { event: 'Napoleon crowns himself Emperor of the French', year: 1804 },
  { event: 'Napoleon is defeated at the Battle of Waterloo', year: 1815 },
  { event: 'Michael Faraday demonstrates electromagnetic induction', year: 1831 },
  { event: 'Samuel Morse sends his first long-distance telegraph message', year: 1844 },
  { event: 'The California Gold Rush begins after gold is found at Sutter\'s Mill', year: 1848 },
  { event: 'Charles Darwin publishes On the Origin of Species', year: 1859 },
  { event: 'Slavery is abolished in the United States by the Thirteenth Amendment', year: 1865 },
  { event: 'The first transcontinental railroad is completed with the golden spike', year: 1869 },
  { event: 'Albert Einstein publishes his special theory of relativity (E=mc²)', year: 1905 },
  { event: 'Henry Ford introduces the Model T automobile', year: 1908 },
  { event: 'Albert Einstein completes his general theory of relativity', year: 1915 },
  { event: 'The first \'talkie\' feature film, The Jazz Singer, premieres', year: 1927 },
  { event: 'Clyde Tombaugh discovers Pluto', year: 1930 },
  { event: 'Amelia Earhart becomes the first woman to fly solo across the Atlantic', year: 1932 },
  { event: 'The first programmable electronic computer ENIAC is unveiled', year: 1946 },
  { event: 'Jackie Robinson breaks Major League Baseball\'s color barrier', year: 1947 },
  { event: 'The Beatles make their first appearance on The Ed Sullivan Show', year: 1964 },
  { event: 'Pong, one of the first commercially successful video games, is released', year: 1972 },
  { event: 'Apple Computer is founded by Steve Jobs and Steve Wozniak', year: 1976 },
  { event: 'The first test-tube baby, Louise Brown, is born', year: 1978 },
  { event: 'IBM releases its first personal computer (the IBM PC)', year: 1981 },
  { event: 'Sally Ride becomes the first American woman in space', year: 1983 },
  { event: 'Dolly the sheep, the first mammal cloned from an adult cell, is born', year: 1996 },
  { event: 'IBM\'s Deep Blue defeats world chess champion Garry Kasparov', year: 1997 },
  { event: 'Google is founded by Larry Page and Sergey Brin', year: 1998 },
  { event: 'The first long-term crew arrives to live aboard the International Space Station', year: 2000 },
  { event: 'The Human Genome Project is completed', year: 2003 },
  { event: 'NASA\'s Curiosity rover lands on Mars', year: 2012 },
  { event: 'Scientists at CERN announce the discovery of the Higgs boson', year: 2012 },
  { event: 'The Rosetta mission lands the Philae probe on a comet', year: 2014 },
  { event: 'Scientists announce the first direct detection of gravitational waves (LIGO)', year: 2016 },
  { event: 'Astronomers release the first-ever image of a black hole', year: 2019 },
];

// ---- Odd one out: { items: [4], oddIndex, rule } (one item breaks a hidden rule) ----
export const ODD_ONE_OUT = [
  { items: ['Apple', 'Banana', 'Carrot', 'Cherry'], oddIndex: 2, rule: 'the others are fruits, carrot is a vegetable' },
  { items: ['Dog', 'Shark', 'Whale', 'Dolphin'], oddIndex: 0, rule: 'the others live in the sea' },
  { items: ['Triangle', 'Square', 'Circle', 'Pentagon'], oddIndex: 2, rule: 'the others have straight sides' },
  { items: ['Mercury', 'Venus', 'Moon', 'Mars'], oddIndex: 2, rule: 'the others are planets, the Moon is a satellite' },
  { items: ['Red', 'Green', 'Blue', 'Square'], oddIndex: 3, rule: 'the others are colours' },
  { items: ['Piano', 'Violin', 'Trumpet', 'Drum'], oddIndex: 2, rule: 'the others are not brass instruments' },
  { items: ['2', '4', '7', '8'], oddIndex: 2, rule: 'the others are even numbers' },
  { items: ['Lion', 'Tiger', 'Leopard', 'Wolf'], oddIndex: 3, rule: 'the others are big cats' },
  { items: ['Gold', 'Silver', 'Iron', 'Bronze'], oddIndex: 2, rule: 'the others are Olympic medal metals' },
  { items: ['Spain', 'France', 'Brazil', 'Italy'], oddIndex: 2, rule: 'the others are in Europe' },
  { items: ['Spring', 'Summer', 'Monday', 'Winter'], oddIndex: 2, rule: 'the others are seasons' },
  { items: ['Oak', 'Pine', 'Rose', 'Maple'], oddIndex: 2, rule: 'the others are trees' },
  { items: ['Snake', 'Lizard', 'Frog', 'Crocodile'], oddIndex: 2, rule: 'the others are reptiles, the frog is an amphibian' },
  { items: ['Eagle', 'Bat', 'Sparrow', 'Owl'], oddIndex: 1, rule: 'the others are birds, the bat is a mammal' },
  { items: ['Whale', 'Dolphin', 'Shark', 'Seal'], oddIndex: 2, rule: 'the others are mammals, the shark is a fish' },
  { items: ['Square', 'Cube', 'Triangle', 'Circle'], oddIndex: 1, rule: 'the others are 2D shapes, the cube is 3D' },
  { items: ['Copper', 'Gold', 'Plastic', 'Silver'], oddIndex: 2, rule: 'the others are metals' },
  { items: ['Coffee', 'Tea', 'Cola', 'Bread'], oddIndex: 3, rule: 'the others are drinks' },
  { items: ['11', '17', '23', '24'], oddIndex: 3, rule: 'the others are odd numbers' },
  { items: ['Mars', 'Saturn', 'Pluto', 'Neptune'], oddIndex: 2, rule: 'the others are planets, Pluto is a dwarf planet' },
  { items: ['Banana', 'Lemon', 'Sun', 'Grass'], oddIndex: 3, rule: 'the others are yellow' },
  { items: ['Penguin', 'Ostrich', 'Eagle', 'Emu'], oddIndex: 2, rule: 'the others are flightless birds' },
  { items: ['London', 'Paris', 'Tokyo', 'Sydney'], oddIndex: 3, rule: 'the others are capital cities' },
  { items: ['Carrot', 'Potato', 'Onion', 'Apple'], oddIndex: 3, rule: 'the others grow underground' },
  { items: ['Mercury', 'Venus', 'Earth', 'Saturn'], oddIndex: 3, rule: 'the others are rocky planets, Saturn is a gas giant' },
  { items: ['Trumpet', 'Trombone', 'Tuba', 'Violin'], oddIndex: 3, rule: 'the others are brass instruments' },
  { items: ['Pacific', 'Atlantic', 'Mediterranean', 'Indian'], oddIndex: 2, rule: 'the others are oceans, the Mediterranean is a sea' },
  { items: ['Rose', 'Tulip', 'Daisy', 'Oak'], oddIndex: 3, rule: 'the others are flowers, the oak is a tree' },
  { items: ['Square', 'Rectangle', 'Rhombus', 'Triangle'], oddIndex: 3, rule: 'the others have four sides' },
  { items: ['Violet', 'Indigo', 'Brown', 'Blue'], oddIndex: 2, rule: 'the others are colours of the rainbow' },
  { items: ['Helium', 'Neon', 'Nitrogen', 'Argon'], oddIndex: 2, rule: 'the others are noble gases (Group 18); nitrogen is not a noble gas' },
  { items: ['Mercury', 'Venus', 'Jupiter', 'Mars'], oddIndex: 2, rule: 'the others are rocky terrestrial planets; Jupiter is a gas giant' },
  { items: ['Tomato', 'Cucumber', 'Lettuce', 'Pepper'], oddIndex: 2, rule: 'the others are botanically fruits (they contain seeds); lettuce is a leafy vegetable' },
  { items: ['Femur', 'Tibia', 'Radius', 'Fibula'], oddIndex: 2, rule: 'the others are bones of the leg; the radius is a bone of the arm' },
  { items: ['Diamond', 'Graphite', 'Quartz', 'Graphene'], oddIndex: 2, rule: 'the others are allotropes of carbon; quartz is silicon dioxide' },
  { items: ['Oak', 'Maple', 'Pine', 'Birch'], oddIndex: 2, rule: 'the others are deciduous trees that drop their leaves; pine is an evergreen conifer' },
  { items: ['Gold', 'Silver', 'Oxygen', 'Copper'], oddIndex: 2, rule: 'the others are metals; oxygen is a nonmetal' },
  { items: ['Octopus', 'Squid', 'Tuna', 'Snail'], oddIndex: 2, rule: 'the others are mollusks; a tuna is a fish' },
  { items: ['Ruby', 'Sapphire', 'Emerald', 'Padparadscha'], oddIndex: 2, rule: 'the others are varieties of corundum; emerald is a variety of beryl' },
  { items: ['Spider', 'Scorpion', 'Ant', 'Tick'], oddIndex: 2, rule: 'the others are arachnids with eight legs; an ant is an insect with six legs' },
  { items: ['Saturn', 'Uranus', 'Earth', 'Neptune'], oddIndex: 2, rule: 'the others are giant planets with ring systems; Earth has no rings' },
  { items: ['Mushroom', 'Yeast', 'Fern', 'Mold'], oddIndex: 2, rule: 'the others are fungi; a fern is a plant' },
  { items: ['Sphere', 'Cube', 'Cone', 'Hexagon'], oddIndex: 3, rule: 'the others are three-dimensional solids; a hexagon is a flat two-dimensional shape' },
  { items: ['Iron', 'Calcium', 'Sodium', 'Potassium'], oddIndex: 0, rule: 'the others are alkali or alkaline-earth metals (Group 1 or 2); iron is a transition metal' },
  { items: ['Frog', 'Salamander', 'Lizard', 'Toad'], oddIndex: 2, rule: 'the others are amphibians; a lizard is a reptile' },
  { items: ['Sun', 'Sirius', 'Mars', 'Betelgeuse'], oddIndex: 2, rule: 'the others are stars; Mars is a planet' },
  { items: ['Liver', 'Kidney', 'Trachea', 'Pancreas'], oddIndex: 2, rule: 'the others are solid glandular organs; the trachea is an airway tube of the respiratory system' },
  { items: ['Cactus', 'Aloe', 'Rose', 'Agave'], oddIndex: 2, rule: 'the others are succulents that store water in fleshy tissue; a rose is not a succulent' },
  { items: ['Penguin', 'Ostrich', 'Bat', 'Emu'], oddIndex: 2, rule: 'the others are flightless birds; a bat is a flying mammal' },
  { items: ['Hydrogen', 'Helium', 'Carbon', 'Lithium'], oddIndex: 2, rule: 'the others are among the first three elements by atomic number (1, 2, 3); carbon is element 6' },
  { items: ['Comet', 'Asteroid', 'Galaxy', 'Meteoroid'], oddIndex: 2, rule: 'the others are small bodies that orbit within a solar system; a galaxy is a vast system of billions of stars' },
  { items: ['Cornea', 'Iris', 'Retina', 'Cochlea'], oddIndex: 3, rule: 'the others are parts of the eye; the cochlea is part of the ear' },
  { items: ['Sunflower', 'Daisy', 'Tulip', 'Dandelion'], oddIndex: 2, rule: 'the others are members of the daisy (Asteraceae) family; a tulip is a lily-family plant' },
  { items: ['Mercury', 'Venus', 'Pluto', 'Saturn'], oddIndex: 2, rule: 'the others are planets; Pluto is a dwarf planet' },
  { items: ['Bee', 'Butterfly', 'Spider', 'Beetle'], oddIndex: 2, rule: 'the others are insects with six legs and three body parts; a spider is an eight-legged arachnid' },
  { items: ['Chlorine', 'Bromine', 'Iodine', 'Mercury'], oddIndex: 3, rule: 'the others are halogens (Group 17); mercury is a transition metal' },
  { items: ['Bolivia', 'Paraguay', 'Chile', 'Switzerland'], oddIndex: 2, rule: 'the others are landlocked countries with no sea coast; Chile has a long Pacific coastline' },
  { items: ['French', 'Romanian', 'Albanian', 'Portuguese'], oddIndex: 2, rule: 'the others are Romance languages descended from Latin; Albanian is its own branch of Indo-European' },
  { items: ['Tennis', 'Volleyball', 'Cricket', 'Badminton'], oddIndex: 2, rule: 'the others are net sports where a net divides the court; cricket uses no dividing net' },
  { items: ['Sydney', 'Canberra', 'Brisbane', 'Melbourne'], oddIndex: 1, rule: 'the others are large Australian cities that are NOT the national capital; Canberra is Australia\'s capital' },
  { items: ['Wimbledon', 'US Open', 'The Masters', 'French Open'], oddIndex: 2, rule: 'the others are tennis Grand Slam tournaments; The Masters is a golf major' },
  { items: ['Mandarin', 'Cantonese', 'Korean', 'Hokkien'], oddIndex: 2, rule: 'the others are Sinitic (Chinese) languages of the Sino-Tibetan family; Korean is a Koreanic language' },
  { items: ['Cumin', 'Coriander', 'Cinnamon', 'Fennel'], oddIndex: 2, rule: 'the others are spices made from seeds; cinnamon is made from tree bark' },
  { items: ['Rhône', 'Nile', 'Danube', 'Po'], oddIndex: 2, rule: 'the others flow into the Mediterranean Sea; the Danube flows into the Black Sea' },
  { items: ['Soccer', 'Rugby union', 'American football', 'Field hockey'], oddIndex: 1, rule: 'the others field 11 players per side; rugby union fields 15' },
  { items: ['German', 'French', 'English', 'Italian'], oddIndex: 2, rule: 'the others are official national languages of Switzerland; English is not' },
  { items: ['Cheddar', 'Gouda', 'Feta', 'Parmesan'], oddIndex: 2, rule: 'the others are traditionally made from cow\'s milk; feta is made from sheep\'s (and goat\'s) milk' },
  { items: ['Sahara', 'Gobi', 'Amazon', 'Kalahari'], oddIndex: 2, rule: 'the others are deserts; the Amazon is a tropical rainforest' },
  { items: ['United Kingdom', 'Japan', 'Germany', 'Australia'], oddIndex: 2, rule: 'the others drive on the left side of the road; Germany drives on the right' },
  { items: ['France', 'Germany', 'Switzerland', 'Spain'], oddIndex: 2, rule: 'the others use the euro as their currency; Switzerland uses the Swiss franc' },
  { items: ['Penne', 'Fusilli', 'Risotto', 'Rigatoni'], oddIndex: 2, rule: 'the others are pasta shapes; risotto is a rice dish' },
  { items: ['Madrid', 'Lisbon', 'Geneva', 'Rome'], oddIndex: 2, rule: 'the others are national capital cities; Geneva is not Switzerland\'s capital (Bern is)' },
  { items: ['Basketball', 'Volleyball', 'Chess', 'Handball'], oddIndex: 2, rule: 'the others are Olympic medal sports; chess is not on the Olympic medal programme' },
  { items: ['Arabic', 'Hebrew', 'Greek', 'Persian'], oddIndex: 2, rule: 'the others are written right-to-left; Greek is written left-to-right' },
  { items: ['Orange', 'Lemon', 'Banana', 'Grapefruit'], oddIndex: 2, rule: 'the others are citrus fruits; the banana is not a citrus' },
  { items: ['Superior', 'Michigan', 'Victoria', 'Erie'], oddIndex: 2, rule: 'the others are North American Great Lakes; Lake Victoria is in Africa' },
  { items: ['Carrot', 'Beet', 'Broccoli', 'Radish'], oddIndex: 2, rule: 'the others are root vegetables eaten for their underground part; broccoli is an above-ground flower head' },
  { items: ['Black', 'Green', 'Rooibos', 'Oolong'], oddIndex: 2, rule: 'the others are teas made from the Camellia sinensis plant; rooibos comes from a different plant (Aspalathus linearis)' },
  { items: ['Asia', 'Africa', 'Greenland', 'Europe'], oddIndex: 2, rule: 'the others are continents; Greenland is an island' },
  { items: ['Uno', 'Dos', 'Quattro', 'Tres'], oddIndex: 2, rule: 'the others are Spanish words for numbers; \'quattro\' is Italian (Spanish for four is \'cuatro\')' },
  { items: ['Basketball', 'Volleyball', 'Soccer', 'Water polo'], oddIndex: 2, rule: 'the others are ball games played mainly with the hands; in soccer outfield players may not use their hands' },
];

// ---- Rank It: { category, ordered: [...] } in the CORRECT order (largest/first to smallest/last) ----
export const RANK_SETS = [
  { category: 'Planets by distance from the Sun (closest first)', ordered: ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter'] },
  { category: 'Largest oceans (biggest first)', ordered: ['Pacific', 'Atlantic', 'Indian', 'Arctic'] },
  { category: 'Fastest animals (fastest first)', ordered: ['Peregrine falcon', 'Cheetah', 'Greyhound', 'House cat', 'Snail'] },
  { category: 'Tallest structures (tallest first)', ordered: ['Burj Khalifa', 'Eiffel Tower', 'Statue of Liberty', 'A giraffe'] },
  { category: 'Chronological order (earliest first)', ordered: ['Roman Empire', 'Magna Carta', 'Columbus 1492', 'Moon landing'] },
  { category: 'Number of sides (fewest first)', ordered: ['Triangle', 'Square', 'Pentagon', 'Hexagon', 'Octagon'] },
  { category: 'Months of the year (in order)', ordered: ['January', 'March', 'June', 'September', 'December'] },
  { category: 'Heaviest land animals (heaviest first)', ordered: ['Elephant', 'Rhino', 'Horse', 'Human', 'Cat'] },
  { category: 'Planets by size (largest first)', ordered: ['Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Earth'] },
  { category: 'Rivers by length (longest first)', ordered: ['Nile', 'Amazon', 'Yangtze', 'Mississippi', 'Danube'] },
  { category: 'Events in history (earliest first)', ordered: ['Pyramids of Giza', 'Roman Empire', 'Magna Carta', 'US Independence', 'First Moon landing'] },
  { category: 'Speeds (slowest first)', ordered: ['Snail', 'Walking human', 'Sprinter', 'Cheetah', 'Falcon dive'] },
  { category: 'Animals by size (largest first)', ordered: ['Blue whale', 'Elephant', 'Horse', 'Dog', 'Mouse'] },
  { category: 'Planets by distance from the Sun (farthest first)', ordered: ['Neptune', 'Uranus', 'Saturn', 'Jupiter', 'Mars'] },
  { category: 'Temperatures (coldest first)', ordered: ['Freezing water', 'Room temperature', 'Human body', 'Boiling water'] },
  { category: 'US coins by value (lowest first)', ordered: ['Penny', 'Nickel', 'Dime', 'Quarter'] },
  { category: 'Mountains by height (tallest first)', ordered: ['Everest', 'K2', 'Kangchenjunga', 'Lhotse'] },
  { category: 'Numbers (smallest first)', ordered: ['2', '7', '15', '40', '99'] },
  { category: 'Time units (shortest first)', ordered: ['Second', 'Minute', 'Hour', 'Day', 'Week'] },
  { category: 'Continents by area (largest first)', ordered: ['Asia', 'Africa', 'North America', 'South America', 'Antarctica'] },
  { category: 'Planets by diameter (largest first)', ordered: ['Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Earth'] },
  { category: 'Planets by length of year / orbital period (shortest first)', ordered: ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter'] },
  { category: 'Planets by length of day / rotation period (shortest first)', ordered: ['Jupiter', 'Saturn', 'Neptune', 'Uranus', 'Earth'] },
  { category: 'Inner planets by average surface temperature (hottest first)', ordered: ['Venus', 'Mercury', 'Earth', 'Mars'] },
  { category: 'Largest moons in the Solar System by diameter (largest first)', ordered: ['Ganymede', 'Titan', 'Callisto', 'Io', 'Earth\'s Moon'] },
  { category: 'Electromagnetic spectrum by wavelength (longest first)', ordered: ['Radio waves', 'Microwaves', 'Infrared', 'Visible light', 'Ultraviolet'] },
  { category: 'Visible light colors by wavelength (longest first)', ordered: ['Red', 'Orange', 'Yellow', 'Green', 'Blue', 'Violet'] },
  { category: 'Earth\'s atmosphere layers from the surface upward (lowest first)', ordered: ['Troposphere', 'Stratosphere', 'Mesosphere', 'Thermosphere', 'Exosphere'] },
  { category: 'Earth\'s interior layers from the center outward (innermost first)', ordered: ['Inner core', 'Outer core', 'Mantle', 'Crust'] },
  { category: 'Continents by land area (largest first)', ordered: ['Asia', 'Africa', 'North America', 'South America', 'Antarctica', 'Europe'] },
  { category: 'Oceans by surface area (largest first)', ordered: ['Pacific', 'Atlantic', 'Indian', 'Southern', 'Arctic'] },
  { category: 'Largest islands in the world by area (largest first)', ordered: ['Greenland', 'New Guinea', 'Borneo', 'Madagascar', 'Baffin Island'] },
  { category: 'Highest mountains on Earth by elevation (tallest first)', ordered: ['Mount Everest', 'K2', 'Kangchenjunga', 'Lhotse', 'Makalu'] },
  { category: 'The Great Lakes by surface area (largest first)', ordered: ['Lake Superior', 'Lake Huron', 'Lake Michigan', 'Lake Erie', 'Lake Ontario'] },
  { category: 'Deepest lakes in the world by maximum depth (deepest first)', ordered: ['Lake Baikal', 'Lake Tanganyika', 'Caspian Sea', 'Lake Vostok', 'O\'Higgins-San Martin Lake'] },
  { category: 'Mohs hardness scale minerals (hardest first)', ordered: ['Diamond', 'Corundum', 'Topaz', 'Quartz', 'Orthoclase'] },
  { category: 'Tallest land mammals by shoulder height (tallest first)', ordered: ['Giraffe', 'Elephant', 'Moose', 'Camel', 'Bison'] },
  { category: 'Minerals by Mohs hardness (softest first)', ordered: ['Talc', 'Gypsum', 'Calcite', 'Fluorite', 'Apatite'] },
  { category: 'Geological eons of Earth (oldest first)', ordered: ['Hadean', 'Archean', 'Proterozoic', 'Phanerozoic'] },
  { category: 'Cryogenic substances by boiling/sublimation point (coldest first)', ordered: ['Liquid helium', 'Liquid nitrogen', 'Liquid oxygen', 'Dry ice'] },
  { category: 'U.S. paper bills by face value (lowest first)', ordered: ['$1', '$5', '$10', '$20', '$50', '$100'] },
  { category: 'Bridge card suits by rank (lowest first)', ordered: ['Clubs', 'Diamonds', 'Hearts', 'Spades'] },
  { category: 'Metric prefixes by the value they multiply (smallest first)', ordered: ['milli', 'centi', 'deci', 'deka', 'hecto', 'kilo'] },
  { category: 'Boxing weight classes by limit (lightest first)', ordered: ['Flyweight', 'Bantamweight', 'Featherweight', 'Lightweight', 'Welterweight'] },
  { category: 'Summer Olympic host cities in chronological order (earliest first)', ordered: ['Beijing', 'London', 'Rio de Janeiro', 'Tokyo', 'Paris'] },
  { category: 'Powers of two in increasing value (smallest first)', ordered: ['2', '4', '8', '16', '32', '64'] },
  { category: 'Units of time by duration (shortest first)', ordered: ['Second', 'Minute', 'Hour', 'Day', 'Week', 'Year'] },
  { category: 'Roman numerals by value (smallest first)', ordered: ['I', 'V', 'X', 'L', 'C', 'D'] },
  { category: 'Fibonacci numbers (smallest first)', ordered: ['1', '2', '3', '5', '8', '13'] },
  { category: 'U.S. units of length by size (shortest first)', ordered: ['Inch', 'Foot', 'Yard', 'Mile'] },
  { category: 'Geologic time spans by length (shortest first)', ordered: ['Epoch', 'Period', 'Era', 'Eon'] },
  { category: 'Prime numbers in increasing order (smallest first)', ordered: ['2', '3', '5', '7', '11', '13'] },
  { category: 'Triangular numbers in sequence order (smallest first)', ordered: ['1', '3', '6', '10', '15', '21'] },
];

// ---- This or That: { prompt, a, b, correct: 'a'|'b' } binary fact. The picker randomly
// swaps which side a fact sits on (see pickThisOrThat) so there is no positional A/B bias. ----
export const THIS_OR_THAT = [
  { prompt: 'Larger by land area?', a: 'Russia', b: 'Canada', correct: 'a' },
  { prompt: 'Closer to the Sun?', a: 'Earth', b: 'Mars', correct: 'a' },
  { prompt: 'Faster top speed?', a: 'Cheetah', b: 'Greyhound', correct: 'a' },
  { prompt: 'Taller?', a: 'Eiffel Tower', b: 'Statue of Liberty', correct: 'a' },
  { prompt: 'Heavier?', a: 'Blue whale', b: 'Elephant', correct: 'a' },
  { prompt: 'More legs?', a: 'Spider', b: 'Insect', correct: 'a' },
  { prompt: 'Happened earlier?', a: 'Moon landing', b: 'First iPhone', correct: 'a' },
  { prompt: 'Longer river?', a: 'Nile', b: 'Thames', correct: 'a' },
  { prompt: 'Bigger planet?', a: 'Jupiter', b: 'Earth', correct: 'a' },
  { prompt: 'Hotter?', a: 'Boiling water', b: 'Freezing water', correct: 'a' },
  { prompt: 'More keys?', a: 'Piano', b: 'Guitar', correct: 'a' },
  { prompt: 'Older invention?', a: 'Printing press', b: 'The internet', correct: 'a' },
  { prompt: 'Larger ocean?', a: 'Pacific', b: 'Atlantic', correct: 'a' },
  { prompt: 'More sides?', a: 'Octagon', b: 'Hexagon', correct: 'a' },
  { prompt: 'Bigger country by area?', a: 'Brazil', b: 'France', correct: 'a' },
  { prompt: 'Came first?', a: 'Dinosaurs', b: 'Humans', correct: 'a' },
  { prompt: 'Larger population?', a: 'Russia', b: 'China', correct: 'b' },
  { prompt: 'Taller building?', a: 'Burj Khalifa', b: 'Empire State Building', correct: 'a' },
  { prompt: 'Faster?', a: 'Sound', b: 'Light', correct: 'b' },
  { prompt: 'Bigger?', a: 'The Sun', b: 'Jupiter', correct: 'a' },
  { prompt: 'Denser metal?', a: 'Lead', b: 'Aluminium', correct: 'a' },
  { prompt: 'Built earlier?', a: 'Pyramids of Giza', b: 'The Colosseum', correct: 'a' },
  { prompt: 'Larger ocean?', a: 'Indian', b: 'Arctic', correct: 'a' },
  { prompt: 'More native speakers?', a: 'English', b: 'Mandarin Chinese', correct: 'b' },
  { prompt: 'Hotter surface?', a: 'Venus', b: 'Mercury', correct: 'a' },
  { prompt: 'Bigger?', a: 'The Moon', b: 'Pluto', correct: 'a' },
  { prompt: 'More legs?', a: 'Crab', b: 'Insect', correct: 'a' },
  { prompt: 'Heavier animal?', a: 'Elephant', b: 'Hippo', correct: 'a' },
  { prompt: 'Older invention?', a: 'The wheel', b: 'The telescope', correct: 'a' },
  { prompt: 'Came first?', a: 'World War I', b: 'World War II', correct: 'a' },
  { prompt: 'Larger by area?', a: 'Canada', b: 'United States', correct: 'a' },
  { prompt: 'Taller animal?', a: 'Giraffe', b: 'Elephant', correct: 'a' },
  { prompt: 'Deeper ocean?', a: 'Pacific', b: 'Atlantic', correct: 'a' },
  { prompt: 'Closer to the Sun?', a: 'Venus', b: 'Mars', correct: 'a' },
  { prompt: 'Larger continent?', a: 'Africa', b: 'Antarctica', correct: 'a' },
  { prompt: 'Smaller planet?', a: 'Mercury', b: 'Mars', correct: 'a' },
  { prompt: 'Hotter?', a: 'Boiling water', b: 'Human body', correct: 'a' },
  { prompt: 'Faster?', a: 'Passenger jet', b: 'Bullet train', correct: 'a' },
  { prompt: 'More moons?', a: 'Saturn', b: 'Earth', correct: 'a' },
  { prompt: 'Larger by area?', a: 'Greenland', b: 'Australia', correct: 'b' },
  { prompt: 'Heavier?', a: 'Blue whale', b: 'African elephant', correct: 'a' },
  { prompt: 'More abundant in air?', a: 'Nitrogen', b: 'Oxygen', correct: 'a' },
  { prompt: 'Built earlier?', a: 'The Great Wall of China', b: 'The Eiffel Tower', correct: 'a' },
  { prompt: 'Lives longer (typically)?', a: 'Tortoise', b: 'Mouse', correct: 'a' },
  { prompt: 'Faster?', a: 'Cheetah', b: 'Diving falcon', correct: 'b' },
  { prompt: 'More sides?', a: 'Hexagon', b: 'Pentagon', correct: 'a' },
  { prompt: 'Larger by total area?', a: 'Australia', b: 'Brazil', correct: 'b' },
  { prompt: 'Larger desert by area?', a: 'Sahara', b: 'Antarctic Desert', correct: 'b' },
  { prompt: 'Larger by area: the Sahara Desert or the whole of Australia?', a: 'Sahara Desert', b: 'Australia', correct: 'a' },
  { prompt: 'Larger lake by surface area?', a: 'Lake Superior', b: 'Lake Victoria', correct: 'a' },
  { prompt: 'Larger lake by surface area?', a: 'Lake Baikal', b: 'Caspian Sea', correct: 'b' },
  { prompt: 'Deeper lake (maximum depth)?', a: 'Lake Baikal', b: 'Lake Tanganyika', correct: 'a' },
  { prompt: 'Holds more water by volume?', a: 'Lake Michigan', b: 'Lake Superior', correct: 'b' },
  { prompt: 'Deeper ocean by average depth?', a: 'Pacific Ocean', b: 'Atlantic Ocean', correct: 'a' },
  { prompt: 'Larger ocean by area?', a: 'Indian Ocean', b: 'Pacific Ocean', correct: 'b' },
  { prompt: 'Taller mountain above sea level?', a: 'Mount Kilimanjaro', b: 'Mount Elbrus', correct: 'a' },
  { prompt: 'Higher peak above sea level?', a: 'Denali', b: 'Aconcagua', correct: 'b' },
  { prompt: 'Highest peak above sea level?', a: 'Mount Everest', b: 'K2', correct: 'a' },
  { prompt: 'Taller measured from base to summit?', a: 'Mount Everest', b: 'Mauna Kea', correct: 'b' },
  { prompt: 'Taller waterfall (total drop)?', a: 'Angel Falls', b: 'Niagara Falls', correct: 'a' },
  { prompt: 'Larger continent by land area?', a: 'Africa', b: 'South America', correct: 'a' },
  { prompt: 'Larger continent by land area?', a: 'Europe', b: 'Antarctica', correct: 'b' },
  { prompt: 'Smaller country by area?', a: 'Vatican City', b: 'Monaco', correct: 'a' },
  { prompt: 'Larger island by area?', a: 'Madagascar', b: 'Borneo', correct: 'b' },
  { prompt: 'Larger island by area?', a: 'Greenland', b: 'New Guinea', correct: 'a' },
  { prompt: 'Longer river?', a: 'Mississippi', b: 'Nile', correct: 'b' },
  { prompt: 'Carries more water (greater discharge)?', a: 'Amazon', b: 'Nile', correct: 'a' },
  { prompt: 'Faster top recorded speed?', a: 'Cheetah', b: 'Peregrine falcon', correct: 'b' },
  { prompt: 'Faster land animal at a sprint?', a: 'Cheetah', b: 'Pronghorn', correct: 'a' },
  { prompt: 'Taller animal?', a: 'Giraffe', b: 'African elephant', correct: 'a' },
  { prompt: 'Taller bird?', a: 'Emu', b: 'Ostrich', correct: 'b' },
  { prompt: 'Larger planet by diameter?', a: 'Earth', b: 'Mars', correct: 'a' },
  { prompt: 'Larger planet by diameter?', a: 'Neptune', b: 'Jupiter', correct: 'b' },
  { prompt: 'Larger sea by area?', a: 'Mediterranean Sea', b: 'Caribbean Sea', correct: 'b' },
  { prompt: 'Lower in elevation (the lowest exposed land on Earth)?', a: 'Dead Sea shore', b: 'Death Valley', correct: 'a' },
  { prompt: 'Which planet is closer to the Sun?', a: 'Mercury', b: 'Venus', correct: 'a' },
  { prompt: 'Which is the largest planet in the solar system?', a: 'Jupiter', b: 'Saturn', correct: 'a' },
  { prompt: 'Which planet has more known moons?', a: 'Jupiter', b: 'Saturn', correct: 'b' },
  { prompt: 'Which planet is the least dense (would float in water)?', a: 'Saturn', b: 'Neptune', correct: 'a' },
  { prompt: 'Which planet has the longer day (rotation period)?', a: 'Mercury', b: 'Mars', correct: 'a' },
  { prompt: 'Which is the longest bone in the human body?', a: 'Tibia', b: 'Femur', correct: 'b' },
  { prompt: 'Which is the smallest bone in the human body?', a: 'Stapes (in the ear)', b: 'Coccyx', correct: 'a' },
  { prompt: 'Which does a newborn baby have more of?', a: 'Bones (~270)', b: 'Bones than an adult\'s 206', correct: 'a' },
  { prompt: 'Which is the largest organ of the human body?', a: 'Liver', b: 'Skin', correct: 'b' },
  { prompt: 'Which is the largest internal organ?', a: 'Liver', b: 'Heart', correct: 'a' },
  { prompt: 'Which is faster?', a: 'Speed of light', b: 'Speed of sound', correct: 'a' },
  { prompt: 'Which element has the lower atomic number?', a: 'Helium', b: 'Hydrogen', correct: 'b' },
  { prompt: 'How many chromosomes are in a typical human body cell?', a: '23', b: '46', correct: 'b' },
  { prompt: 'Which has the longer lifespan in the body?', a: 'A red blood cell (~120 days)', b: 'A neutrophil (~1 day)', correct: 'a' },
  { prompt: 'How many moons does Earth have?', a: 'One', b: 'Two', correct: 'a' },
  { prompt: 'A light-year measures which of these?', a: 'Distance', b: 'Time', correct: 'a' },
  { prompt: 'What is the Sun classified as?', a: 'A star', b: 'A planet', correct: 'a' },
  { prompt: 'What is the chemical formula for water?', a: 'CO2', b: 'H2O', correct: 'b' },
  { prompt: 'Which part of the eye controls how much light enters?', a: 'The pupil', b: 'The cornea', correct: 'a' },
  { prompt: 'Which gas do humans exhale more of than they inhale?', a: 'Oxygen', b: 'Carbon dioxide', correct: 'b' },
  { prompt: 'Which blood vessels carry blood away from the heart?', a: 'Veins', b: 'Arteries', correct: 'b' },
  { prompt: 'Which planet is known as the \'Red Planet\'?', a: 'Mars', b: 'Jupiter', correct: 'a' },
  { prompt: 'Which planet in our solar system is farthest from the Sun?', a: 'Uranus', b: 'Neptune', correct: 'b' },
  { prompt: 'Which organ produces insulin?', a: 'Pancreas', b: 'Kidney', correct: 'a' },
  { prompt: 'Which has more chambers?', a: 'The human heart (4)', b: 'A 3-chamber model', correct: 'a' },
  { prompt: 'Which is the largest muscle in the human body?', a: 'Biceps', b: 'Gluteus maximus', correct: 'b' },
  { prompt: 'Which is denser?', a: 'Earth', b: 'Saturn', correct: 'a' },
  { prompt: 'Which scientist is most associated with the theory of general relativity?', a: 'Isaac Newton', b: 'Albert Einstein', correct: 'b' },
  { prompt: 'Dedicated FIRST?', a: 'The Eiffel Tower', b: 'The Statue of Liberty', correct: 'b' },
  { prompt: 'Invented FIRST?', a: 'The typewriter', b: 'The ballpoint pen', correct: 'a' },
  { prompt: 'Taller mountain?', a: 'Mount Kilimanjaro', b: 'Mont Blanc', correct: 'a' },
  { prompt: 'Came FIRST in history?', a: 'The U.S. Declaration of Independence (1776)', b: 'The French Revolution (1789)', correct: 'a' },
  { prompt: 'Patented FIRST?', a: 'The telephone', b: 'Edison\'s practical light bulb', correct: 'a' },
  { prompt: 'Larger ocean by area?', a: 'The Pacific Ocean', b: 'The Atlantic Ocean', correct: 'a' },
  { prompt: 'Came FIRST in history?', a: 'The Gutenberg printing press', b: 'The Magna Carta', correct: 'b' },
  { prompt: 'Came FIRST in history?', a: 'The first ancient Olympic Games', b: 'The founding of the Roman Empire', correct: 'a' },
  { prompt: 'Has a barbed stinger and dies after stinging?', a: 'The honey bee', b: 'The wasp', correct: 'a' },
  { prompt: 'Happened FIRST?', a: 'World War I began', b: 'The Titanic sank', correct: 'b' },
  { prompt: 'Botanically a true berry?', a: 'The tomato', b: 'The strawberry', correct: 'a' },
  { prompt: 'Happened FIRST?', a: 'The first Moon landing', b: 'The fall of the Berlin Wall', correct: 'a' },
  { prompt: 'The fastest LAND animal?', a: 'The peregrine falcon', b: 'The cheetah', correct: 'b' },
  { prompt: 'Came FIRST in history?', a: 'Columbus\'s first voyage to the Americas', b: 'The birth of Shakespeare', correct: 'a' },
  { prompt: 'Harder material?', a: 'Diamond', b: 'Graphite', correct: 'a' },
  { prompt: 'Created FIRST?', a: 'Pepsi', b: 'Coca-Cola', correct: 'b' },
  { prompt: 'Larger desert by area?', a: 'The Sahara Desert', b: 'The Arabian Desert', correct: 'a' },
  { prompt: 'Featured on the U.S. one-dollar bill?', a: 'Abraham Lincoln', b: 'George Washington', correct: 'b' },
  { prompt: 'Came FIRST?', a: 'The first automobile (Benz)', b: 'The Wright brothers\' first flight', correct: 'a' },
  { prompt: 'More acidic (lower pH)?', a: 'A lemon', b: 'An orange', correct: 'a' },
  { prompt: 'Came FIRST?', a: 'The first email', b: 'The World Wide Web', correct: 'a' },
  { prompt: 'Higher-pitched string instrument?', a: 'The violin', b: 'The cello', correct: 'a' },
  { prompt: 'Larger Roman numeral value?', a: 'C', b: 'X', correct: 'a' },
  { prompt: 'Invented FIRST in China?', a: 'Paper', b: 'Gunpowder', correct: 'a' },
  { prompt: 'Has FEWER legs?', a: 'A spider', b: 'An insect', correct: 'b' },
  { prompt: 'Completed FIRST?', a: 'The Sistine Chapel ceiling (1512)', b: 'The Eiffel Tower (1889)', correct: 'a' },
];

function pick(list, n, exclude = []) {
  const ex = new Set(exclude);
  const pool = shuffle(list.filter((_, i) => !ex.has(i)));
  return pool.slice(0, n);
}

export function pickMultipleChoice(n = 1, exclude = []) { return pick(MULTIPLE_CHOICE, n, exclude); }
export function pickNumericFacts(n = 1, exclude = []) { return pick(NUMERIC_FACTS, n, exclude); }
export function pickEvents(n = 1, exclude = []) { return pick(EVENTS, n, exclude); }
export function pickOddOneOut(n = 1, exclude = []) { return pick(ODD_ONE_OUT, n, exclude); }
export function pickRankSets(n = 1, exclude = []) { return pick(RANK_SETS, n, exclude); }

// Randomly flips each picked fact's A/B sides (and its correct key) so there is no
// positional bias — a player can't just "always pick A" to win.
export function pickThisOrThat(n = 1, exclude = []) {
  return pick(THIS_OR_THAT, n, exclude).map((q) => (
    Math.random() < 0.5
      ? { ...q, a: q.b, b: q.a, correct: q.correct === 'a' ? 'b' : 'a' }
      : { ...q }
  ));
}

export function shuffledQuantities() { return shuffle(QUANTITIES); }
export { shuffle };
