export const WORDS = [
  // 5-letter words
  'about', 'above', 'abuse', 'actor', 'acute', 'admit', 'adopt', 'adult', 'after',
  'again', 'agent', 'agree', 'ahead', 'alarm', 'album', 'alert', 'alien', 'align',
  'alive', 'alley', 'allow', 'alone', 'along', 'alter', 'amaze', 'ample', 'angel',
  'anger', 'angle', 'angry', 'ankle', 'apart', 'apple', 'arena', 'armor', 'arrow',
  'aside', 'asset', 'attic', 'audio', 'await', 'awake', 'award', 'aware', 'badge',
  'baker', 'basic', 'basin', 'batch', 'beach', 'beast', 'begin', 'belly', 'bench',
  'berry', 'bible', 'birth', 'black', 'blade', 'blame', 'bland', 'blank', 'blast',
  'blaze', 'bleed', 'blend', 'bless', 'blind', 'blink', 'bliss', 'block', 'blood',
  'bloom', 'blown', 'board', 'bonus', 'booth', 'bound', 'brain', 'brand', 'brave',
  'bread', 'break', 'breed', 'brick', 'bride', 'brief', 'bring', 'broad', 'brook',
  'broom', 'brush', 'buddy', 'build', 'bunch', 'bunny', 'burst', 'buyer', 'cabin',
  'cable', 'camel', 'candy', 'cargo', 'carry', 'catch', 'cause', 'cedar', 'chain',
  'chair', 'chalk', 'champ', 'chant', 'chaos', 'charm', 'chart', 'chase', 'cheap',
  'check', 'cheer', 'chess', 'chest', 'chief', 'child', 'chill', 'choir', 'chunk',
  'civic', 'civil', 'claim', 'clash', 'class', 'clean', 'clear', 'clerk', 'cliff',
  'climb', 'cling', 'clock', 'clone', 'close', 'cloth', 'cloud', 'clown', 'coach',
  'coast', 'comet', 'comic', 'coral', 'couch', 'count', 'court', 'cover', 'crack',
  'craft', 'crane', 'crash', 'crazy', 'cream', 'creek', 'crisp', 'cross', 'crowd',
  'crown', 'crush', 'curve', 'cycle', 'dairy', 'dance', 'decay', 'delay', 'delta',
  'demon', 'depth', 'derby', 'devil', 'diary', 'dirty', 'disco', 'ditch', 'dizzy',
  'doubt', 'dough', 'draft', 'drain', 'drake', 'drama', 'dream', 'dress', 'drift',
  'drill', 'drink', 'drive', 'drown', 'dusty', 'dwarf', 'dwell', 'eager', 'eagle',
  'earth', 'eight', 'elbow', 'elder', 'elect', 'elite', 'ember', 'empty', 'enemy',
  'enjoy', 'entry', 'equal', 'error', 'event', 'every', 'exact', 'exile', 'exist',
  'extra', 'fable', 'faint', 'fairy', 'faith', 'fancy', 'fatal', 'fault', 'feast',
  'fence', 'fetch', 'fever', 'fiber', 'field', 'fifty', 'fight', 'final', 'first',
  'flame', 'flash', 'flask', 'fleet', 'flesh', 'flick', 'flint', 'float', 'flock',
  'flood', 'floor', 'flora', 'flour', 'fluid', 'flute', 'focus', 'foggy', 'force',
  'forge', 'forth', 'forum', 'found', 'frame', 'frank', 'fraud', 'fresh', 'front',
  'frost', 'froze', 'fruit', 'fully', 'funny', 'fuzzy', 'ghost', 'giant', 'given',
  'glade', 'glass', 'gleam', 'globe', 'gloom', 'glory', 'gloss', 'glove', 'going',
  'grace', 'grade', 'grain', 'grand', 'grant', 'grape', 'graph', 'grasp', 'grass',
  'grave', 'great', 'greed', 'green', 'greet', 'grief', 'grind', 'groan', 'groom',
  'gross', 'group', 'grove', 'growl', 'grown', 'guard', 'guess', 'guest', 'guide',
  'guild', 'guilt', 'guise', 'gummy', 'habit', 'happy', 'harsh', 'haste', 'haunt',
  'haven', 'heart', 'heavy', 'hedge', 'heist', 'hello', 'hence', 'herbs', 'hilly',
  'hinge', 'hobby', 'honey', 'honor', 'horse', 'hotel', 'house', 'human', 'humor',
  'hurry', 'hyper', 'ideal', 'image', 'imply', 'index', 'indie', 'inner', 'input',
  'issue', 'ivory', 'jewel', 'joint', 'joker', 'jolly', 'judge', 'juice', 'jumbo',
  'karma', 'kayak', 'kebab', 'kinky', 'knack', 'kneel', 'knife', 'knock', 'known',
  'label', 'labor', 'lance', 'large', 'laser', 'latch', 'later', 'laugh', 'layer',
  'leach', 'leash', 'least', 'leave', 'lemon', 'level', 'lever', 'light', 'lilac',
  'limit', 'linen', 'liver', 'llama', 'lobby', 'local', 'lodge', 'logic', 'loose',
  'lorry', 'lover', 'lower', 'loyal', 'lucky', 'lunar', 'lunch', 'lyric', 'magic',
  'major', 'maker', 'manor', 'maple', 'march', 'marsh', 'mason', 'match', 'mayor',
  'medal', 'media', 'melon', 'mercy', 'merge', 'merit', 'merry', 'metal', 'meter',
  'might', 'miner', 'minor', 'minus', 'mirth', 'mixer', 'model', 'month', 'moose',
  'moral', 'motto', 'mound', 'mount', 'mourn', 'mouse', 'mouth', 'movie', 'muddy',
  'music', 'mystic', 'naive', 'nerve', 'never', 'night', 'noble', 'noise', 'north',
  'notch', 'noted', 'novel', 'nudge', 'nurse', 'nylon', 'ocean', 'occur', 'offer',
  'olive', 'onset', 'opera', 'orbit', 'order', 'organ', 'other', 'ought', 'outer',
  'outdo', 'owner', 'oxide', 'ozone', 'paint', 'panel', 'panic', 'paper', 'party',
  'pasta', 'paste', 'patch', 'pause', 'peace', 'peach', 'pearl', 'pedal', 'penny',
  'perch', 'phase', 'phone', 'photo', 'piano', 'piece', 'pilot', 'pinch', 'pitch',
  'pixel', 'pizza', 'place', 'plaid', 'plain', 'plane', 'plank', 'plant', 'plate',
  'plaza', 'plead', 'pluck', 'plumb', 'plume', 'plump', 'point', 'polar', 'porch',
  'pouch', 'pound', 'power', 'press', 'price', 'pride', 'prime', 'print', 'prior',
  'prize', 'probe', 'prone', 'proof', 'proud', 'prune', 'pulse', 'punch', 'pupil',
  'puppy', 'purse', 'queen', 'quest', 'queue', 'quiet', 'quilt', 'quirk', 'quota',
  'quote', 'radar', 'radio', 'raise', 'rally', 'ranch', 'range', 'rapid', 'ratio',
  'raven', 'reach', 'realm', 'rebel', 'refer', 'reign', 'relax', 'rider', 'ridge',
  'rifle', 'rigid', 'rinse', 'risen', 'risky', 'rival', 'river', 'roast', 'robin',
  'robot', 'rocky', 'rogue', 'rouge', 'rough', 'round', 'route', 'rover', 'royal',
  'rugby', 'ruler', 'rural', 'rusty', 'sadly', 'saint', 'salad', 'sauce', 'savor',
  'scale', 'scare', 'scene', 'scent', 'scope', 'score', 'scout', 'scrap', 'setup',
  'seven', 'shade', 'shaft', 'shake', 'shame', 'shape', 'share', 'shark', 'sharp',
  'shave', 'sheep', 'sheer', 'sheet', 'shelf', 'shell', 'shift', 'shine', 'shirt',
  'shock', 'shoot', 'shore', 'short', 'shout', 'shown', 'siege', 'sight', 'silly',
  'since', 'sixth', 'sixty', 'sized', 'skill', 'skull', 'slate', 'sleep', 'slice',
  'slide', 'slope', 'smart', 'smell', 'smile', 'smith', 'smoke', 'snack', 'snake',
  'snowy', 'solar', 'solid', 'solve', 'sonic', 'sorry', 'south', 'space', 'spare',
  'spark', 'speak', 'spear', 'speed', 'spell', 'spend', 'spice', 'spike', 'spine',
  'spite', 'split', 'spoke', 'spoon', 'sport', 'spray', 'squad', 'stack', 'staff',
  'stage', 'stain', 'stair', 'stake', 'stale', 'stalk', 'stall', 'stamp', 'stand',
  'stark', 'start', 'state', 'steak', 'steal', 'steam', 'steel', 'steep', 'steer',
  'stern', 'stick', 'stiff', 'still', 'sting', 'stock', 'stole', 'stone', 'stood',
  'stool', 'store', 'storm', 'story', 'stout', 'stove', 'strap', 'straw', 'strip',
  'stuck', 'study', 'stuff', 'stump', 'style', 'sugar', 'suite', 'sunny', 'super',
  'surge', 'swamp', 'swear', 'sweep', 'sweet', 'swept', 'swift', 'swing', 'swirl',
  'sword', 'syrup', 'table', 'taste', 'teach', 'teeth', 'tempo', 'thick', 'thief',
  'thing', 'think', 'third', 'thorn', 'those', 'three', 'threw', 'throw', 'thumb',
  'tiger', 'tight', 'timer', 'title', 'toast', 'token', 'topic', 'torch', 'total',
  'touch', 'tough', 'towel', 'tower', 'toxic', 'track', 'trade', 'trail', 'train',
  'trait', 'trash', 'treat', 'trend', 'trial', 'tribe', 'trick', 'troop', 'truck',
  'truly', 'trump', 'trunk', 'trust', 'truth', 'tulip', 'tuner', 'twice', 'twist',
  'ultra', 'uncle', 'under', 'union', 'unite', 'unity', 'until', 'upper', 'upset',
  'urban', 'usage', 'usual', 'utter', 'valid', 'value', 'vapor', 'vault', 'venue',
  'verge', 'verse', 'vigor', 'vinyl', 'viola', 'viral', 'virus', 'visit', 'vivid',
  'vocal', 'vodka', 'voice', 'voter', 'vowel', 'wagon', 'waist', 'waste', 'watch',
  'water', 'weary', 'weave', 'wedge', 'weigh', 'weird', 'whale', 'wheat', 'wheel',
  'where', 'which', 'while', 'white', 'whole', 'whose', 'wider', 'witch', 'woman',
  'world', 'worry', 'worse', 'worst', 'worth', 'would', 'wound', 'wrath', 'write',
  'wrong', 'wrote', 'yacht', 'yield', 'young', 'youth', 'zebra',

  // 6-letter words
  'absorb', 'accept', 'access', 'across', 'action', 'active', 'actual', 'admire',
  'advent', 'affirm', 'afford', 'agenda', 'almost', 'always', 'amount', 'anchor',
  'animal', 'annual', 'answer', 'anthem', 'anyone', 'anyway', 'appeal', 'append',
  'arctic', 'artist', 'aspect', 'assert', 'assign', 'assist', 'assume', 'assure',
  'attach', 'attack', 'attend', 'author', 'bakery', 'ballet', 'bamboo', 'banana',
  'banker', 'banner', 'barely', 'barrel', 'basket', 'battle', 'beacon', 'beauty',
  'became', 'become', 'before', 'behalf', 'behave', 'behind', 'belong', 'beside',
  'better', 'beyond', 'bishop', 'bitter', 'blanch', 'blazer', 'blonde', 'borrow',
  'bounce', 'branch', 'breath', 'breeze', 'bridge', 'bright', 'bronze', 'bruise',
  'bubble', 'bucket', 'budget', 'buffer', 'bundle', 'burden', 'burner', 'butter',
  'button', 'cabana', 'cactus', 'camera', 'campus', 'candle', 'canyon', 'carbon',
  'carpet', 'carrot', 'castle', 'cattle', 'caught', 'cellar', 'center', 'cereal',
  'chance', 'change', 'chapel', 'charge', 'cheese', 'cherry', 'choice', 'choose',
  'chosen', 'church', 'circle', 'circus', 'clever', 'client', 'closet', 'clover',
  'cobalt', 'coffee', 'colony', 'combat', 'comedy', 'coming', 'commit', 'common',
  'comply', 'convey', 'cookie', 'cooler', 'copper', 'corner', 'costly', 'cotton',
  'county', 'couple', 'course', 'cousin', 'cradle', 'create', 'credit', 'crisis',
  'cruise', 'custom', 'damage', 'dampen', 'dancer', 'danger', 'daring', 'darken',
  'debate', 'debris', 'decade', 'decent', 'decide', 'decode', 'decree', 'defect',
  'defend', 'define', 'degree', 'demand', 'depart', 'deploy', 'deputy', 'derive',
  'desert', 'design', 'desire', 'detail', 'detect', 'device', 'devote', 'dialog',
  'differ', 'digest', 'dinner', 'direct', 'divide', 'domain', 'donkey', 'double',
  'dragon', 'drawer', 'driver', 'duplex', 'during', 'easily', 'eating', 'effect',
  'effort', 'eighth', 'either', 'eleven', 'emerge', 'empire', 'employ', 'enable',
  'endure', 'energy', 'engage', 'engine', 'enough', 'ensure', 'entire', 'entity',
  'eraser', 'escape', 'estate', 'evenly', 'evolve', 'exceed', 'except', 'excite',
  'excuse', 'exempt', 'expand', 'expect', 'expert', 'export', 'extend', 'extent',
  'fabric', 'facial', 'factor', 'fairly', 'falcon', 'family', 'famine', 'famous',
  'farmer', 'faucet', 'fellow', 'female', 'ferret', 'fiction', 'figure', 'filter',
  'finale', 'finger', 'finish', 'flavor', 'flight', 'flower', 'fluffy', 'flying',
  'follow', 'forbid', 'forced', 'forest', 'forged', 'forget', 'forgive', 'formal',
  'format', 'former', 'fossil', 'foster', 'fourth', 'freeze', 'frenzy', 'friend',
  'frisky', 'frozen', 'frugal', 'funnel', 'furry', 'future', 'gadget', 'galaxy',
  'gamble', 'garage', 'garden', 'garlic', 'gather', 'gazebo', 'gently', 'geyser',
  'ginger', 'global', 'glider', 'glossy', 'goblet', 'golden', 'gossip', 'gravel',
  'groove', 'ground', 'growth', 'grumpy', 'guitar', 'gutter', 'hammer', 'hamper',
  'handle', 'happen', 'harbor', 'hardly', 'hassle', 'hasten', 'hazard', 'healer',
  'health', 'hearts', 'heaven', 'height', 'helmet', 'helper', 'hereby', 'hidden',
  'holder', 'hollow', 'homage', 'honest', 'hoodie', 'hornet', 'horror', 'humble',
  'hunger', 'hunter', 'hurdle', 'hustle', 'hybrid', 'ignore', 'impact', 'import',
  'impose', 'income', 'indeed', 'indoor', 'infant', 'inform', 'inject', 'injury',
  'inning', 'insect', 'insert', 'inside', 'insist', 'intact', 'intend', 'intent',
  'invent', 'invest', 'invite', 'island', 'italic', 'itself', 'jacket', 'jigsaw',
  'jingle', 'jogger', 'jumble', 'jumper', 'jungle', 'junior', 'karate', 'kennel',
  'kernel', 'kettle', 'kidnap', 'killer', 'kindly', 'kitten', 'knight', 'ladder',
  'lagoon', 'lament', 'lariat', 'launch', 'lavish', 'lawyer', 'layout', 'leader',
  'league', 'learnt', 'legacy', 'legend', 'lender', 'lesson', 'letter', 'linear',
  'linger', 'liquid', 'listen', 'litter', 'little', 'lively', 'lizard', 'locker',
  'locket', 'lonely', 'looker', 'lovely', 'luxury', 'magnet', 'maiden', 'mallet',
  'manage', 'manner', 'mantle', 'manual', 'marble', 'margin', 'marine', 'market',
  'marvel', 'master', 'matrix', 'matter', 'meadow', 'medium', 'melody', 'memoir',
  'memory', 'mental', 'mentor', 'method', 'middle', 'mighty', 'mingle', 'minute',
  'mirror', 'misery', 'mobile', 'modern', 'modest', 'modify', 'molten', 'moment',
  'monkey', 'morsel', 'mortar', 'mostly', 'motion', 'muffin', 'mumble', 'museum',
  'muzzle', 'myself', 'napkin', 'narrow', 'nation', 'nature', 'nearby', 'nearly',
  'neatly', 'needle', 'nephew', 'nestle', 'nickel', 'nimble', 'ninety', 'noodle',
  'normal', 'notice', 'notion', 'number', 'nutmeg', 'object', 'obtain', 'occupy',
  'oddity', 'office', 'offset', 'online', 'oppose', 'option', 'oracle', 'orange',
  'orchid', 'orient', 'origin', 'outfit', 'outlet', 'output', 'outrun', 'oxygen',
  'oyster', 'paddle', 'palace', 'pantry', 'parade', 'parcel', 'parent', 'parrot',
  'patrol', 'patron', 'paving', 'pebble', 'pencil', 'people', 'pepper', 'permit',
  'person', 'phrase', 'picket', 'pickle', 'picnic', 'pillar', 'pillow', 'pirate',
  'planet', 'player', 'plenty', 'pledge', 'pliers', 'plunge', 'pocket', 'poetry',
  'poison', 'policy', 'polite', 'ponder', 'poplar', 'portal', 'poster', 'potato',
  'potion', 'potter', 'poultry', 'powder', 'prayer', 'prefer', 'pretty', 'prince',
  'prison', 'profit', 'prompt', 'propel', 'proven', 'public', 'puddle', 'punish',
  'puppet', 'purple', 'pursue', 'puzzle', 'quaint', 'quartz', 'rabbit', 'racket',
  'radish', 'random', 'ranger', 'ransom', 'raptor', 'rascal', 'rattle', 'ravine',
  'reason', 'reboot', 'recall', 'recipe', 'record', 'redeem', 'reduce', 'reform',
  'refuge', 'refund', 'refuse', 'regard', 'region', 'regret', 'reject', 'relate',
  'relief', 'remain', 'remedy', 'remote', 'remove', 'render', 'rental', 'repair',
  'repeat', 'report', 'rescue', 'resign', 'resist', 'resort', 'result', 'resume',
  'retail', 'retain', 'retire', 'return', 'reveal', 'review', 'revolt', 'reward',
  'ribbon', 'riddle', 'ripple', 'ritual', 'robust', 'rocket', 'roller', 'rookie',
  'rubber', 'ruffle', 'rumble', 'runner', 'rustic', 'saddle', 'safari', 'safety',
  'sailor', 'salary', 'salmon', 'saloon', 'salute', 'sample', 'sandal', 'saving',
  'saying', 'scenic', 'school', 'script', 'scroll', 'search', 'season', 'second',
  'secret', 'secure', 'select', 'sender', 'senior', 'series', 'sermon', 'settle',
  'shadow', 'shield', 'shiver', 'shovel', 'shower', 'shrewd', 'shroud', 'signal',
  'silver', 'simple', 'simply', 'singer', 'single', 'sketch', 'sleeve', 'slogan',
  'slowly', 'smooth', 'snatch', 'soccer', 'socket', 'soften', 'source', 'speech',
  'spirit', 'splash', 'sponge', 'spooky', 'spring', 'sprint', 'square', 'stable',
  'statue', 'steady', 'stolen', 'stormy', 'stove', 'strain', 'strand', 'streak',
  'stream', 'street', 'strict', 'stride', 'strike', 'string', 'stripe', 'strive',
  'strong', 'studio', 'submit', 'subtle', 'sudden', 'suffix', 'summer', 'summit',
  'summon', 'sunset', 'superb', 'supply', 'supper', 'surely', 'survey', 'switch',
  'symbol', 'syntax', 'system', 'tablet', 'tackle', 'tailor', 'talent', 'target',
  'temple', 'tenant', 'tender', 'tennis', 'terror', 'thirst', 'thorny', 'thread',
  'thrift', 'thrive', 'throne', 'ticket', 'tidy', 'timber', 'tissue', 'tomato',
  'tongue', 'toward', 'travel', 'treaty', 'tribal', 'triple', 'trophy', 'tumble',
  'tunnel', 'turkey', 'turtle', 'twelve', 'unfair', 'unfold', 'unique', 'united',
  'unless', 'unlike', 'unload', 'unlock', 'unrest', 'unsung', 'untold', 'unveil',
  'upbeat', 'update', 'uphill', 'upkeep', 'upload', 'upward', 'urgent', 'utmost',
  'utopia', 'valley', 'vandal', 'vanish', 'varied', 'velvet', 'vendor', 'verbal',
  'verify', 'vessel', 'victim', 'violet', 'virtue', 'vision', 'visual', 'vivid',
  'volume', 'voyage', 'waffle', 'walnut', 'wander', 'walrus', 'wallet', 'warden',
  'warmth', 'wealth', 'weapon', 'weasel', 'weekly', 'weight', 'wicked', 'widget',
  'willow', 'window', 'winner', 'winter', 'wisdom', 'within', 'wonder', 'wooden',
  'worker', 'worthy', 'wreath', 'writer', 'yellow', 'zenith', 'zigzag', 'zombie',
];
