import { TIMERS } from './constants.js';

export const GAMES = {
  blackjack: {
    id: 'blackjack', name: 'Blackjack', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME, description: 'Beat the dealer. Closest to 21 wins.',
    tutorial: 'https://www.youtube.com/watch?v=TDkbWXJ16hU',
  },
  poker: {
    id: 'poker', name: 'Texas Hold\'em', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME, description: 'Best hand wins the pot.',
    tutorial: 'https://www.youtube.com/watch?v=b9HYxquQt-M',
  },
  uno: {
    id: 'uno', name: 'Uno', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME, description: 'First to empty your hand wins.',
    tutorial: 'https://www.youtube.com/watch?v=sWoSZmHsCls',
  },
  goFish: {
    id: 'goFish', name: 'Go Fish', minPlayers: 2, maxPlayers: 6,
    turnTimer: TIMERS.CARD_GAME, description: 'Collect the most sets of four.',
    tutorial: 'https://www.youtube.com/watch?v=emvdufe6t-8',
  },
  crazyEights: {
    id: 'crazyEights', name: 'Crazy Eights', minPlayers: 2, maxPlayers: 6,
    turnTimer: TIMERS.CARD_GAME, description: 'Match suit or rank. First to empty hand wins.',
    tutorial: 'https://www.youtube.com/watch?v=1c4YPQTS35I',
  },
  rps: {
    id: 'rps', name: 'Rock Paper Scissors', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.RPS, description: 'Best of 5. Choose wisely.',
    tutorial: 'https://www.youtube.com/watch?v=2dsHuU10udY',
  },
  liarsDice: {
    id: 'liarsDice', name: 'Liar\'s Dice', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME, description: 'Bluff or call. Last player with dice wins.',
    tutorial: 'https://www.youtube.com/watch?v=fAbnMuiR734',
  },
  memoryMatch: {
    id: 'memoryMatch', name: 'Memory Match', minPlayers: 2, maxPlayers: 6,
    turnTimer: TIMERS.CARD_GAME, description: 'Flip pairs. Best memory wins.',
    tutorial: 'https://www.youtube.com/watch?v=wQV5RJKs_qI',
  },
  roulette: {
    id: 'roulette', name: 'Roulette', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.ROULETTE, description: 'Place your bets. Highest winnings ranks first.',
    tutorial: 'https://www.youtube.com/watch?v=YuePFYmplm0',
  },
  hangman: {
    id: 'hangman', name: 'Hangman', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME, description: 'Guess the word. Fewest wrong guesses wins.',
    tutorial: 'https://www.youtube.com/watch?v=leW9ZotUVYo',
  },
  spotTheDifference: {
    id: 'spotTheDifference', name: 'Spot the Difference', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.SPOT_DIFFERENCE, description: 'Race to find differences between two grids. First to spot wins!',
    instructions: [
      'Two grids of colored shapes are shown side by side — one is the original, the other has been modified.',
      'Click on any cell where you spot a difference between the two grids (color, shape, size, or rotation).',
      'First player to click a difference gets +150 points. Wrong clicks cost -25 points with a 1-second cooldown.',
      'There are 3 rounds with increasing difficulty: 5, 7, then 9 differences to find.',
      'Each round has a 45-second timer. The round ends when all differences are found or time runs out.',
      'Highest total score across all rounds wins!',
    ],
  },
  battleship: {
    id: 'battleship', name: 'Battleship', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.BATTLESHIP, description: 'Place your fleet and sink your opponent\'s ships!',
    tutorial: 'https://www.youtube.com/watch?v=RY4nAyRgkLo',
    instructions: [
      'Place 5 ships on your 10×10 grid during the setup phase (60 seconds).',
      'Ships: Carrier (5), Battleship (4), Cruiser (3), Submarine (3), Destroyer (2).',
      'Take turns firing at your opponent\'s grid. Hits are red, misses are white.',
      'Hit a ship = fire again! Miss = opponent\'s turn.',
      'Sink all 5 of your opponent\'s ships to win.',
    ],
  },
  reactionTap: {
    id: 'reactionTap', name: 'Reaction Tap', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.REACTION_TAP,
    description: 'Wait for green, then tap. Fastest reflexes win.',
    instructions: [
      'Each round shows a red WAIT screen. Do NOT tap while it is red.',
      'After a random delay (1.5–5s) the screen turns green and says GO — tap as fast as you can.',
      'Tapping while red is a foul (max 3000ms penalty). Not tapping in time also scores the max.',
      'Your reaction time in milliseconds is recorded by the server (lower is better).',
      'Play 5 rounds; the lowest total reaction time across all rounds wins.',
      'Note: your network latency is included in the measured time — the server times your tap on its own clock and never trusts the browser, so results are spoof-proof but slightly favor faster connections.',
    ],
  },
  typingRace: {
    id: 'typingRace', name: 'Typing Race', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.TYPING,
    description: 'Transcribe the scroll fastest. First to finish wins the sprint.',
    instructions: [
      'A passage from an ancient scroll appears — type it exactly as written.',
      'Your typing is checked live: a wrong character stops your progress until you fix it (backspace and retype).',
      'Watch the race track — every player\'s marker crawls toward the finish line in real time.',
      'You have 90 seconds. First player to finish the whole passage ranks highest.',
      'If time runs out, players are ranked by how many correct characters they typed, then by speed.',
      'Your WPM (words per minute) is shown live and frozen when you finish.',
    ],
  },
  scattergories: {
    id: 'scattergories', name: 'Scattergories', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.SCATTERGORIES,
    description: 'One letter, ten categories. Be the only one with each answer.',
    instructions: [
      'Each round a random letter and 10 categories appear.',
      'Type one answer per category that STARTS with the letter, before the 75-second timer runs out.',
      'An answer scores 1 point only if it is valid AND unique — if two or more players write the same thing, nobody gets the point.',
      'Empty answers and answers that do not start with the letter score 0.',
      'During the reveal you can flag a rival\'s answer as fake — if EVERY other player flags it, it is removed and scores nothing.',
      'There are 3 rounds. Highest total of unique answers wins!',
    ],
  },
  bsCheat: {
    id: 'bsCheat', name: 'BS (Cheat)', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Bluff your cards away. Call BS to bust the liar — first to empty their hand escapes.',
    instructions: [
      'Cards are dealt evenly and the claimed rank cycles A, 2, 3 … K each turn.',
      'On your turn place 1–4 cards FACE DOWN and claim they are the current rank (e.g. "two Kings").',
      'Other players get a few seconds to call BS. First to call wins the challenge.',
      'If the claim was a lie, the liar takes the whole pile. If it was true, the challenger takes it.',
      'Empty your hand to escape — the last player still holding cards loses. Finish earliest to place highest.',
    ],
  },
  wavelength: {
    id: 'wavelength', name: 'Wavelength', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.WAVELENGTH_CLUE,
    description: 'Read the psychic\'s mind. Slide to the hidden target on the spectrum.',
    instructions: [
      'Each sub-round one player is the Psychic and sees a hidden target band on a spectrum (e.g. Cold ↔ Hot).',
      'The Psychic writes one short clue (no numbers!) hinting where the target sits.',
      'Everyone else slides a marker from 0 to 100 to guess the band — guesses stay hidden until reveal.',
      'Bullseye = 4 pts, close = 3, near = 2, miss = 0. The Psychic scores from how well the guessers did (capped at 4).',
      'Every player is Psychic once. Highest total across all sub-rounds wins the round!',
    ],
  },
  aimTrainer: {
    id: 'aimTrainer', name: 'Aim Trainer Duel', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.AIM,
    description: 'Hit as many targets as you can in 25 seconds. Fastest aim wins.',
    instructions: [
      'When the round starts, a target appears in your own play area.',
      'Click or tap the target as fast as you can — each hit instantly spawns the next one.',
      'You have 25 seconds. Every player gets their own private stream of targets, so it is perfectly fair.',
      'Most hits wins the round. If tied, the higher accuracy (hits ÷ clicks) ranks first.',
      'Clicking empty space counts as a miss and lowers your accuracy — aim, do not spray.',
    ],
  },
  mastermind: {
    id: 'mastermind', name: 'Mastermind', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.MASTERMIND,
    description: 'Crack the secret code. First to break it wins.',
    instructions: [
      'Everyone races to crack the SAME hidden 4-peg code (6 colors, duplicates allowed).',
      'Submit a guess of 4 colors. You get feedback: black = right color AND right spot, white = right color WRONG spot.',
      'Your board is private — opponents only see whether you solved it and how many guesses you used.',
      'You get up to 10 guesses and 120 seconds. First to crack it (fewest guesses, then fastest) ranks highest.',
      'If nobody cracks it, you rank by best progress — most black pegs, then most white.',
    ],
  },
  president: {
    id: 'president', name: 'President', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Shed your hand first to rule. Last one stuck is the Scumlord.',
    instructions: [
      'Everyone is dealt the whole deck. Card order low to high: 3,4,5,6,7,8,9,10,J,Q,K,A,2 (2 is highest).',
      'The leader plays any group of same-rank cards (single, pair, triple, or four).',
      'On your turn, beat the pile with a higher group of the SAME size, or pass.',
      'Once you pass you are out until the trick clears. When all but one player passes, that player leads a fresh trick.',
      'Empty your hand to finish. First out is President, last left is Scumlord. Your finish order is your ranking.',
    ],
  },
  spoons: {
    id: 'spoons', name: 'Spoons', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.SPOONS_GRAB,
    description: 'Pass cards fast, get four of a kind, then GRAB a spoon. Last one out each round is gone.',
    instructions: [
      'Everyone holds 4 cards. There is always one fewer spoon than players.',
      'Cards flow around the table — pick up the card coming to you, then tap one card to pass on.',
      'The instant someone gets four of a kind, the GRAB phase opens for everyone.',
      'Tap as fast as you can — the one player left without a spoon is eliminated.',
      'Survive each round. The last player standing wins; finishing order sets your placement.',
    ],
  },
  connect4: {
    id: 'connect4', name: 'Connect 4', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Drop discs, get four in a row. 1v1 matchups across a best-of-3 ladder.',
    instructions: [
      'You are paired 1v1 against another player each mini-round (odd player count = one free-win bye).',
      'Take turns dropping a disc into a column — it falls to the lowest empty slot.',
      'First to line up four of your discs in a row (across, down, or diagonally) wins the match.',
      'Full board with no four-in-a-row = a draw (counts as half a win for both).',
      'Win your matches across 3 mini-rounds; the most wins ranks first. Slowpokes get a random drop after 30s.',
    ],
  },
  ultimateTTT: {
    id: 'ultimateTTT', name: 'Ultimate Tic-Tac-Toe', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Nine tic-tac-toe boards in one. Win three boards in a row. 1v1 best-of-3 ladder.',
    instructions: [
      'You are paired 1v1 each mini-round (odd player count = one free-win bye).',
      'The big board is 9 small tic-tac-toe boards. Win a small board to claim its big-board cell.',
      'The cell you play in decides which small board your opponent must play in next.',
      'If you are sent to a board that is already finished, you may play in any open board.',
      'Win three small boards in a row to win the match. Most wins across 3 mini-rounds ranks first.',
    ],
  },
  fibbage: {
    id: 'fibbage', name: 'Fibbage', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.FIBBAGE_WRITE,
    description: 'Bluff your friends with a fake answer to an obscure question. Spot the truth, fool the rest.',
    instructions: [
      'Each round shows an obscure trivia question with a blank.',
      'Everyone secretly writes a FAKE answer to fool others (you cannot reuse the real answer or someone else\'s fib).',
      'All fakes plus the REAL answer are shuffled and shown. Pick the one you think is true — you can\'t pick your own fib.',
      'Score +1000 for finding the truth, and +500 for every player your fib fools.',
      'Highest total after 4 questions wins the round!',
    ],
  },
  skribbl: {
    id: 'skribbl', name: 'Skribbl', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.SKRIBBL_TURN,
    description: 'One player draws a secret word, everyone else races to guess it.',
    instructions: [
      'Each player takes a turn drawing a secret word; everyone else guesses in the chat box.',
      'Only the drawer sees the word — guessers get blanks showing its length.',
      'Type your guess: the faster you get it, the more points you score.',
      'The drawer earns points for every player who guesses it. The drawer cannot guess.',
      'Everyone draws once. Highest total points ranks first.',
    ],
  },
  telephonePictionary: {
    id: 'telephonePictionary', name: 'Telephone Pictionary', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.TELEPHONE_STEP,
    description: 'Write a phrase, draw the last one, guess the last drawing. Chaos by reveal.',
    instructions: [
      'Everyone secretly writes a starting phrase.',
      'Each step you get the page before you: draw the phrase, or guess the drawing.',
      'You only ever see the ONE thing right before you — never the whole chain.',
      'Steps alternate draw / write and rotate around the table until every page is full.',
      'All chains are revealed one frame at a time — watch the phrase mutate into nonsense.',
      'Vote for the funniest chain. Most votes + taking part scores you the round.',
    ],
  },
  othello: {
    id: 'othello', name: 'Othello', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Bracket and flip your rival\'s discs to own the most of the board. 1v1 best-of-3 ladder.',
    instructions: [
      'You are paired 1v1 each mini-round (odd player count = one free-win bye).',
      'Black moves first. Place a disc so it sandwiches a straight line of your opponent\'s discs between it and one of yours.',
      'Every opponent disc you bracket (in any of 8 directions) flips to your colour.',
      'You can only play moves that flip at least one disc; with no legal move your turn is auto-passed.',
      'When neither player can move, the most discs wins. Win matches across 3 mini-rounds to rank first.',
    ],
  },
  dotsAndBoxes: {
    id: 'dotsAndBoxes', name: 'Dots & Boxes', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Draw the fourth side to claim a box and go again. 1v1 best-of-3 ladder.',
    instructions: [
      'You are paired 1v1 each mini-round (odd player count = one free-win bye).',
      'Take turns drawing one line between two adjacent dots on the 5x5 grid.',
      'Complete the 4th side of a box to claim it — and immediately take another turn.',
      'Chain your captures, but beware handing your rival a long chain at the end.',
      'When all 25 boxes are filled, the most boxes wins. Win matches across 3 mini-rounds to rank first.',
    ],
  },
  gomoku: {
    id: 'gomoku', name: 'Gomoku', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Five stones in a row on a 15x15 board. 1v1 best-of-3 ladder.',
    instructions: [
      'You are paired 1v1 each mini-round (odd player count = one free-win bye).',
      'Black moves first; players alternate placing one stone on an empty intersection.',
      'Get five or more of your stones in an unbroken line — across, down, or diagonally — to win the board.',
      'Block your rival\'s lines while building your own.',
      'Win matches across 3 mini-rounds; the most wins ranks first.',
    ],
  },
  hex: {
    id: 'hex', name: 'Hex', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Connect your two edges with an unbroken chain. 1v1 best-of-3 ladder — never a draw.',
    instructions: [
      'You are paired 1v1 each mini-round (odd player count = one free-win bye).',
      'Take turns placing one stone on any empty cell of the 11x11 rhombus.',
      'If you own the top & bottom edges, win by linking them with a connected chain; otherwise link left & right.',
      'Stones connect through 6 hex neighbours (both diagonals count) — plan winding paths and block your foe.',
      'Hex can never tie. Win matches across 3 mini-rounds to rank first.',
    ],
  },
  orderChaos: {
    id: 'orderChaos', name: 'Order & Chaos', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'One player wants five in a row, the other wants to stop it. 1v1 best-of-3 ladder.',
    instructions: [
      'Each match pits Order against Chaos on a 6x6 board (roles shown to you).',
      'On your turn place EITHER an X or an O on any empty cell — both players use both symbols.',
      'Order wins instantly if any line of five identical symbols appears (row, column, or diagonal).',
      'Chaos wins if the board fills up with no five-in-a-row anywhere.',
      'Win matches across 3 mini-rounds to climb the standings.',
    ],
  },
  nim: {
    id: 'nim', name: 'Nim Heist', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Raid the gem stacks — but grab the last gem and you lose. 1v1 best-of-3 ladder.',
    instructions: [
      'You are paired 1v1 each mini-round (odd player count = one free-win bye).',
      'Three stacks of gems sit on the table; on your turn take any number of gems from ONE stack.',
      'Players alternate, each removing at least one gem from a single stack.',
      'Misère twist: whoever is forced to take the very last gem LOSES.',
      'Win your 1v1 matches across the mini-rounds to climb the Swiss standings.',
    ],
  },
  buzzerRoyale: {
    id: 'buzzerRoyale', name: 'Buzzer Royale', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Multiple-choice buzzer trivia — lock the right answer fastest to score the most.',
    instructions: [
      'Each question shows 4 choices (A/B/C/D) to everyone at the same time.',
      'Tap a choice to buzz in and lock it — you get one lock per question.',
      'Speed matters: the first to lock the correct answer scores most, decaying for each later correct buzz.',
      'A wrong buzz scores 0 and locks you out of that question, so don\'t guess blindly.',
      'Highest cumulative score across 8 questions wins.',
    ],
  },
  higherLower: {
    id: 'higherLower', name: 'Higher or Lower', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Is the next quantity higher or lower? Build a survival streak — miss and you\'re out.',
    instructions: [
      'A CURRENT card shows a quantity and its value; a NEXT card shows only a label, value hidden.',
      'Everyone still in simultaneously taps HIGHER or LOWER for the next value vs the current one.',
      'Correct callers survive and their streak grows; wrong callers are eliminated.',
      'Equal values are a push — nobody is out. The revealed item becomes the new anchor.',
      'Longest streak ranks first; ties share a placement.',
    ],
  },
  priceIsWrong: {
    id: 'priceIsWrong', name: 'Price Is Wrong', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Guess the real number — closest WITHOUT going over wins the round.',
    instructions: [
      'Each round shows a fact prompt and the unit to answer in.',
      'Privately type one numeric guess and lock it in.',
      'Closest guess without going over the true answer scores the most; ties share the payout.',
      'Go over the real answer and you score 0 that round.',
      'Highest cumulative score across 5 rounds wins.',
    ],
  },
  timeline: {
    id: 'timeline', name: 'Timeline', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Guess the year of historical events on a slider — closer is more points.',
    instructions: [
      'Each round shows a historical event.',
      'Drag the slider (1400–2025) to your best guess for the year and lock it in.',
      'Score is higher the closer you are; an exact hit is worth the most.',
      'Guesses are private until the reveal, which shows the true year and everyone\'s markers.',
      'Highest cumulative score over 6 events wins; ties share a placement.',
    ],
  },
  guesstimate: {
    id: 'guesstimate', name: 'Guesstimate', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Order-of-magnitude estimation — being within a factor still scores big.',
    instructions: [
      'Each round shows a numeric prompt (e.g. "Height of the Eiffel Tower").',
      'Privately type your best positive-number guess and lock it in.',
      'Scoring is log-relative: an exact guess is best, a 10× miss still scores decently.',
      'Only wild order-of-magnitude misses are punished, and gently.',
      'Highest cumulative total across 5 rounds wins; ties share a placement.',
    ],
  },
  oddOneOut: {
    id: 'oddOneOut', name: 'Odd One Out', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Spot the item that breaks the hidden rule — fastest correct tap scores most.',
    instructions: [
      'Each round shows 4 items; one breaks a hidden rule.',
      'Tap the odd one out — the faster you\'re correct, the more you score.',
      'A wrong tap scores 0 and locks you out of that round.',
      'The reveal shows the odd item and the rule.',
      'Highest cumulative score across 6 rounds wins.',
    ],
  },
  rankIt: {
    id: 'rankIt', name: 'Rank It', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Put the shuffled items into the correct order — accuracy scores.',
    instructions: [
      'Each round shows a category and a set of items in shuffled order.',
      'Privately reorder them (tap to swap, or use arrows) into the order you think is correct.',
      'Score is based on how many adjacent pairs you got in the right order.',
      'The reveal shows the true order beside yours.',
      'Highest cumulative score across 4 rounds wins; ties share a placement.',
    ],
  },
  thisOrThat: {
    id: 'thisOrThat', name: 'This or That', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Binary trivia survival — answer wrong and you\'re eliminated.',
    instructions: [
      'Each round shows a fact with two options, A and B.',
      'Everyone still in simultaneously taps A or B.',
      'Answer wrong and you\'re eliminated; correct players survive to the next question.',
      'Players knocked out in the same round share a placement.',
      'Last survivor ranks first (reverse-elimination order).',
    ],
  },
};

export function getEligibleGames(playerCount) {
  return Object.values(GAMES).filter(
    (g) => playerCount >= g.minPlayers && playerCount <= g.maxPlayers
  );
}
