import { TIMERS } from './constants.js';

export const GAMES = {
  blackjack: {
    id: 'blackjack', name: 'Blackjack', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME, description: 'Beat the dealer. Closest to 21 wins.',
    tutorial: 'https://www.youtube.com/watch?v=TDkbWXJ16hU',
  },
  poker: {
    id: 'poker', name: 'Texas Hold\'em', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME, description: 'Best hand wins the pot.',
    tutorial: 'https://www.youtube.com/watch?v=b9HYxquQt-M',
  },
  uno: {
    id: 'uno', name: 'Uno', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME, description: 'First to empty your hand wins.',
    tutorial: 'https://www.youtube.com/watch?v=sWoSZmHsCls',
  },
  goFish: {
    id: 'goFish', name: 'Go Fish', minPlayers: 2, maxPlayers: 6,
    turnTimer: TIMERS.CARD_GAME, description: 'Collect the most sets of four.',
    tutorial: 'https://www.youtube.com/watch?v=emvdufe6t-8',
  },
  crazyEights: {
    id: 'crazyEights', name: 'Crazy Eights', minPlayers: 2, maxPlayers: 6,
    turnTimer: TIMERS.CARD_GAME, description: 'Match suit or rank. First to empty hand wins.',
    tutorial: 'https://www.youtube.com/watch?v=1c4YPQTS35I',
  },
  rps: {
    id: 'rps', name: 'Rock Paper Scissors', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.RPS, description: 'Best of 5. Choose wisely.',
    tutorial: 'https://www.youtube.com/watch?v=2dsHuU10udY',
  },
  liarsDice: {
    id: 'liarsDice', name: 'Liar\'s Dice', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME, description: 'Bluff or call. Last player with dice wins.',
    tutorial: 'https://www.youtube.com/watch?v=fAbnMuiR734',
  },
  memoryMatch: {
    id: 'memoryMatch', name: 'Memory Match', minPlayers: 2, maxPlayers: 6,
    turnTimer: TIMERS.CARD_GAME, description: 'Flip pairs. Best memory wins.',
    tutorial: 'https://www.youtube.com/watch?v=wQV5RJKs_qI',
  },
  roulette: {
    id: 'roulette', name: 'Roulette', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.ROULETTE, description: 'Place your bets. Highest winnings ranks first.',
    tutorial: 'https://www.youtube.com/watch?v=YuePFYmplm0',
  },
  hangman: {
    id: 'hangman', name: 'Hangman', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME, description: 'Guess the word. Fewest wrong guesses wins.',
    tutorial: 'https://www.youtube.com/watch?v=leW9ZotUVYo',
  },
  spotTheDifference: {
    id: 'spotTheDifference', name: 'Spot the Difference', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.SPOT_DIFFERENCE, description: 'Race to find differences between two grids. First to spot wins!',
    instructions: [
      'Two grids of colored shapes are shown side by side — one is the original, the other has been modified.',
      'Click on any cell where you spot a difference between the two grids (color, shape, size, or rotation).',
      'First player to click a difference gets +150 points. Wrong clicks cost -25 points with a 1-second cooldown.',
      'There are 3 rounds with increasing difficulty: 5, 7, then 9 differences to find.',
      'Each round has a 45-second timer. The round ends when all differences are found or time runs out.',
      'Highest total score across all rounds wins!',
    ],
  },
  battleship: {
    id: 'battleship', name: 'Battleship', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.BATTLESHIP, description: 'Place your fleet and sink your opponent\'s ships!',
    tutorial: 'https://www.youtube.com/watch?v=RY4nAyRgkLo',
    instructions: [
      'Place 5 ships on your 10×10 grid during the setup phase (60 seconds).',
      'Ships: Carrier (5), Battleship (4), Cruiser (3), Submarine (3), Destroyer (2).',
      'Take turns firing at your opponent\'s grid. Hits are red, misses are white.',
      'Hit a ship = fire again! Miss = opponent\'s turn.',
      'Sink all 5 of your opponent\'s ships to win.',
    ],
  },
  reactionTap: {
    id: 'reactionTap', name: 'Reaction Tap', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.REACTION_TAP,
    description: 'Wait for green, then tap. Fastest reflexes win.',
    instructions: [
      'Each round shows a red WAIT screen. Do NOT tap while it is red.',
      'After a random delay (1.5–5s) the screen turns green and says GO — tap as fast as you can.',
      'Tapping while red is a foul (max 3000ms penalty). Not tapping in time also scores the max.',
      'Your reaction time in milliseconds is recorded by the server (lower is better).',
      'Play 5 rounds; the lowest total reaction time across all rounds wins.',
      'Note: your network latency is included in the measured time — the server times your tap on its own clock and never trusts the browser, so results are spoof-proof but slightly favor faster connections.',
    ],
  },
  typingRace: {
    id: 'typingRace', name: 'Typing Race', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.TYPING,
    description: 'Transcribe the scroll fastest. First to finish wins the sprint.',
    instructions: [
      'A passage from an ancient scroll appears — type it exactly as written.',
      'Your typing is checked live: a wrong character stops your progress until you fix it (backspace and retype).',
      'Watch the race track — every player\'s marker crawls toward the finish line in real time.',
      'You have 90 seconds. First player to finish the whole passage ranks highest.',
      'If time runs out, players are ranked by how many correct characters they typed, then by speed.',
      'Your WPM (words per minute) is shown live and frozen when you finish.',
    ],
  },
  scattergories: {
    id: 'scattergories', name: 'Scattergories', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.SCATTERGORIES,
    description: 'One letter, ten categories. Be the only one with each answer.',
    instructions: [
      'Each round a random letter and 10 categories appear.',
      'Type one answer per category that STARTS with the letter, before the 75-second timer runs out.',
      'An answer scores 1 point only if it is valid AND unique — if two or more players write the same thing, nobody gets the point.',
      'Empty answers and answers that do not start with the letter score 0.',
      'During the reveal you can flag a rival\'s answer as fake — if EVERY other player flags it, it is removed and scores nothing.',
      'There are 3 rounds. Highest total of unique answers wins!',
    ],
  },
  bsCheat: {
    id: 'bsCheat', name: 'BS (Cheat)', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Bluff your cards away. Call BS to bust the liar — first to empty their hand escapes.',
    instructions: [
      'Cards are dealt evenly and the claimed rank cycles A, 2, 3 … K each turn.',
      'On your turn place 1–4 cards FACE DOWN and claim they are the current rank (e.g. "two Kings").',
      'Other players get a few seconds to call BS. First to call wins the challenge.',
      'If the claim was a lie, the liar takes the whole pile. If it was true, the challenger takes it.',
      'Empty your hand to escape — the last player still holding cards loses. Finish earliest to place highest.',
    ],
  },
  wavelength: {
    id: 'wavelength', name: 'Wavelength', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.WAVELENGTH_CLUE,
    description: 'Read the psychic\'s mind. Slide to the hidden target on the spectrum.',
    instructions: [
      'Each sub-round one player is the Psychic and sees a hidden target band on a spectrum (e.g. Cold ↔ Hot).',
      'The Psychic writes one short clue (no numbers!) hinting where the target sits.',
      'Everyone else slides a marker from 0 to 100 to guess the band — guesses stay hidden until reveal.',
      'Bullseye = 4 pts, close = 3, near = 2, miss = 0. The Psychic scores from how well the guessers did (capped at 4).',
      'Every player is Psychic once. Highest total across all sub-rounds wins the round!',
    ],
  },
  aimTrainer: {
    id: 'aimTrainer', name: 'Aim Trainer Duel', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.AIM,
    description: 'Hit as many targets as you can in 25 seconds. Fastest aim wins.',
    instructions: [
      'When the round starts, a target appears in your own play area.',
      'Click or tap the target as fast as you can — each hit instantly spawns the next one.',
      'You have 25 seconds. Every player gets their own private stream of targets, so it is perfectly fair.',
      'Most hits wins the round. If tied, the higher accuracy (hits ÷ clicks) ranks first.',
      'Clicking empty space counts as a miss and lowers your accuracy — aim, do not spray.',
    ],
  },
  mastermind: {
    id: 'mastermind', name: 'Mastermind', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.MASTERMIND,
    description: 'Crack the secret code. First to break it wins.',
    instructions: [
      'Everyone races to crack the SAME hidden 4-peg code (6 colors, duplicates allowed).',
      'Submit a guess of 4 colors. You get feedback: black = right color AND right spot, white = right color WRONG spot.',
      'Your board is private — opponents only see whether you solved it and how many guesses you used.',
      'You get up to 10 guesses and 120 seconds. First to crack it (fewest guesses, then fastest) ranks highest.',
      'If nobody cracks it, you rank by best progress — most black pegs, then most white.',
    ],
  },
  president: {
    id: 'president', name: 'President', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Shed your hand first to rule. Last one stuck is the Scumlord.',
    instructions: [
      'Everyone is dealt the whole deck. Card order low to high: 3,4,5,6,7,8,9,10,J,Q,K,A,2 (2 is highest).',
      'The leader plays any group of same-rank cards (single, pair, triple, or four).',
      'On your turn, beat the pile with a higher group of the SAME size, or pass.',
      'Once you pass you are out until the trick clears. When all but one player passes, that player leads a fresh trick.',
      'Empty your hand to finish. First out is President, last left is Scumlord. Your finish order is your ranking.',
    ],
  },
  spoons: {
    id: 'spoons', name: 'Spoons', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.SPOONS_GRAB,
    description: 'Pass cards fast, get four of a kind, then GRAB a spoon. Last one out each round is gone.',
    instructions: [
      'Everyone holds 4 cards. There is always one fewer spoon than players.',
      'Cards flow around the table — pick up the card coming to you, then tap one card to pass on.',
      'The instant someone gets four of a kind, the GRAB phase opens for everyone.',
      'Tap as fast as you can — the one player left without a spoon is eliminated.',
      'Survive each round. The last player standing wins; finishing order sets your placement.',
    ],
  },
  connect4: {
    id: 'connect4', name: 'Connect 4', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Drop discs, get four in a row. 1v1 matchups across a best-of-3 ladder.',
    instructions: [
      'You are paired 1v1 against another player each mini-round (odd player count = one free-win bye).',
      'Take turns dropping a disc into a column — it falls to the lowest empty slot.',
      'First to line up four of your discs in a row (across, down, or diagonally) wins the match.',
      'Full board with no four-in-a-row = a draw (counts as half a win for both).',
      'Win your matches across 3 mini-rounds; the most wins ranks first. Slowpokes get a random drop after 30s.',
    ],
  },
  ultimateTTT: {
    id: 'ultimateTTT', name: 'Ultimate Tic-Tac-Toe', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Nine tic-tac-toe boards in one. Win three boards in a row. 1v1 best-of-3 ladder.',
    instructions: [
      'You are paired 1v1 each mini-round (odd player count = one free-win bye).',
      'The big board is 9 small tic-tac-toe boards. Win a small board to claim its big-board cell.',
      'The cell you play in decides which small board your opponent must play in next.',
      'If you are sent to a board that is already finished, you may play in any open board.',
      'Win three small boards in a row to win the match. Most wins across 3 mini-rounds ranks first.',
    ],
  },
  fibbage: {
    id: 'fibbage', name: 'Fibbage', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.FIBBAGE_WRITE,
    description: 'Bluff your friends with a fake answer to an obscure question. Spot the truth, fool the rest.',
    instructions: [
      'Each round shows an obscure trivia question with a blank.',
      'Everyone secretly writes a FAKE answer to fool others (you cannot reuse the real answer or someone else\'s fib).',
      'All fakes plus the REAL answer are shuffled and shown. Pick the one you think is true — you can\'t pick your own fib.',
      'Score +1000 for finding the truth, and +500 for every player your fib fools.',
      'Highest total after 4 questions wins the round!',
    ],
  },
  skribbl: {
    id: 'skribbl', name: 'Skribbl', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.SKRIBBL_TURN,
    description: 'One player draws a secret word, everyone else races to guess it.',
    instructions: [
      'Each player takes a turn drawing a secret word; everyone else guesses in the chat box.',
      'Only the drawer sees the word — guessers get blanks showing its length.',
      'Type your guess: the faster you get it, the more points you score.',
      'The drawer earns points for every player who guesses it. The drawer cannot guess.',
      'Everyone draws once. Highest total points ranks first.',
    ],
  },
  telephonePictionary: {
    id: 'telephonePictionary', name: 'Telephone Pictionary', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.TELEPHONE_STEP,
    description: 'Write a phrase, draw the last one, guess the last drawing. Chaos by reveal.',
    instructions: [
      'Everyone secretly writes a starting phrase.',
      'Each step you get the page before you: draw the phrase, or guess the drawing.',
      'You only ever see the ONE thing right before you — never the whole chain.',
      'Steps alternate draw / write and rotate around the table until every page is full.',
      'All chains are revealed one frame at a time — watch the phrase mutate into nonsense.',
      'Vote for the funniest chain. Most votes + taking part scores you the round.',
    ],
  },
  othello: {
    id: 'othello', name: 'Othello', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Bracket and flip your rival\'s discs to own the most of the board. 1v1 best-of-3 ladder.',
    instructions: [
      'You are paired 1v1 each mini-round (odd player count = one free-win bye).',
      'Black moves first. Place a disc so it sandwiches a straight line of your opponent\'s discs between it and one of yours.',
      'Every opponent disc you bracket (in any of 8 directions) flips to your colour.',
      'You can only play moves that flip at least one disc; with no legal move your turn is auto-passed.',
      'When neither player can move, the most discs wins. Win matches across 3 mini-rounds to rank first.',
    ],
  },
  dotsAndBoxes: {
    id: 'dotsAndBoxes', name: 'Dots & Boxes', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Draw the fourth side to claim a box and go again. 1v1 best-of-3 ladder.',
    instructions: [
      'You are paired 1v1 each mini-round (odd player count = one free-win bye).',
      'Take turns drawing one line between two adjacent dots on the 5x5 grid.',
      'Complete the 4th side of a box to claim it — and immediately take another turn.',
      'Chain your captures, but beware handing your rival a long chain at the end.',
      'When all 25 boxes are filled, the most boxes wins. Win matches across 3 mini-rounds to rank first.',
    ],
  },
  gomoku: {
    id: 'gomoku', name: 'Gomoku', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Five stones in a row on a 15x15 board. 1v1 best-of-3 ladder.',
    instructions: [
      'You are paired 1v1 each mini-round (odd player count = one free-win bye).',
      'Black moves first; players alternate placing one stone on an empty intersection.',
      'Get five or more of your stones in an unbroken line — across, down, or diagonally — to win the board.',
      'Block your rival\'s lines while building your own.',
      'Win matches across 3 mini-rounds; the most wins ranks first.',
    ],
  },
  hex: {
    id: 'hex', name: 'Hex', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Connect your two edges with an unbroken chain. 1v1 best-of-3 ladder — never a draw.',
    instructions: [
      'You are paired 1v1 each mini-round (odd player count = one free-win bye).',
      'Take turns placing one stone on any empty cell of the 11x11 rhombus.',
      'If you own the top & bottom edges, win by linking them with a connected chain; otherwise link left & right.',
      'Stones connect through 6 hex neighbours (both diagonals count) — plan winding paths and block your foe.',
      'Hex can never tie. Win matches across 3 mini-rounds to rank first.',
    ],
  },
  orderChaos: {
    id: 'orderChaos', name: 'Order & Chaos', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'One player wants five in a row, the other wants to stop it. 1v1 best-of-3 ladder.',
    instructions: [
      'Each match pits Order against Chaos on a 6x6 board (roles shown to you).',
      'On your turn place EITHER an X or an O on any empty cell — both players use both symbols.',
      'Order wins instantly if any line of five identical symbols appears (row, column, or diagonal).',
      'Chaos wins if the board fills up with no five-in-a-row anywhere.',
      'Win matches across 3 mini-rounds to climb the standings.',
    ],
  },
  nim: {
    id: 'nim', name: 'Nim Heist', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Raid the gem stacks — but grab the last gem and you lose. 1v1 best-of-3 ladder.',
    instructions: [
      'You are paired 1v1 each mini-round (odd player count = one free-win bye).',
      'Three stacks of gems sit on the table; on your turn take any number of gems from ONE stack.',
      'Players alternate, each removing at least one gem from a single stack.',
      'Misère twist: whoever is forced to take the very last gem LOSES.',
      'Win your 1v1 matches across the mini-rounds to climb the Swiss standings.',
    ],
  },
  buzzerRoyale: {
    id: 'buzzerRoyale', name: 'Buzzer Royale', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Multiple-choice buzzer trivia — lock the right answer fastest to score the most.',
    instructions: [
      'Each question shows 4 choices (A/B/C/D) to everyone at the same time.',
      'Tap a choice to buzz in and lock it — you get one lock per question.',
      'Speed matters: the first to lock the correct answer scores most, decaying for each later correct buzz.',
      'A wrong buzz scores 0 and locks you out of that question, so don\'t guess blindly.',
      'Highest cumulative score across 8 questions wins.',
    ],
  },
  higherLower: {
    id: 'higherLower', name: 'Higher or Lower', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Is the next quantity higher or lower? Build a survival streak — miss and you\'re out.',
    instructions: [
      'A CURRENT card shows a quantity and its value; a NEXT card shows only a label, value hidden.',
      'Everyone still in simultaneously taps HIGHER or LOWER for the next value vs the current one.',
      'Correct callers survive and their streak grows; wrong callers are eliminated.',
      'Equal values are a push — nobody is out. The revealed item becomes the new anchor.',
      'Longest streak ranks first; ties share a placement.',
    ],
  },
  priceIsWrong: {
    id: 'priceIsWrong', name: 'Price Is Wrong', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Guess the real number — closest WITHOUT going over wins the round.',
    instructions: [
      'Each round shows a fact prompt and the unit to answer in.',
      'Privately type one numeric guess and lock it in.',
      'Closest guess without going over the true answer scores the most; ties share the payout.',
      'Go over the real answer and you score 0 that round.',
      'Highest cumulative score across 5 rounds wins.',
    ],
  },
  timeline: {
    id: 'timeline', name: 'Timeline', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Guess the year of historical events on a slider — closer is more points.',
    instructions: [
      'Each round shows a historical event.',
      'Drag the slider (1400–2025) to your best guess for the year and lock it in.',
      'Score is higher the closer you are; an exact hit is worth the most.',
      'Guesses are private until the reveal, which shows the true year and everyone\'s markers.',
      'Highest cumulative score over 6 events wins; ties share a placement.',
    ],
  },
  guesstimate: {
    id: 'guesstimate', name: 'Guesstimate', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Order-of-magnitude estimation — being within a factor still scores big.',
    instructions: [
      'Each round shows a numeric prompt (e.g. "Height of the Eiffel Tower").',
      'Privately type your best positive-number guess and lock it in.',
      'Scoring is log-relative: an exact guess is best, a 10× miss still scores decently.',
      'Only wild order-of-magnitude misses are punished, and gently.',
      'Highest cumulative total across 5 rounds wins; ties share a placement.',
    ],
  },
  oddOneOut: {
    id: 'oddOneOut', name: 'Odd One Out', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Spot the item that breaks the hidden rule — fastest correct tap scores most.',
    instructions: [
      'Each round shows 4 items; one breaks a hidden rule.',
      'Tap the odd one out — the faster you\'re correct, the more you score.',
      'A wrong tap scores 0 and locks you out of that round.',
      'The reveal shows the odd item and the rule.',
      'Highest cumulative score across 6 rounds wins.',
    ],
  },
  rankIt: {
    id: 'rankIt', name: 'Rank It', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Put the shuffled items into the correct order — accuracy scores.',
    instructions: [
      'Each round shows a category and a set of items in shuffled order.',
      'Privately reorder them (tap to swap, or use arrows) into the order you think is correct.',
      'Score is based on how many adjacent pairs you got in the right order.',
      'The reveal shows the true order beside yours.',
      'Highest cumulative score across 4 rounds wins; ties share a placement.',
    ],
  },
  thisOrThat: {
    id: 'thisOrThat', name: 'This or That', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Binary trivia survival — answer wrong and you\'re eliminated.',
    instructions: [
      'Each round shows a fact with two options, A and B.',
      'Everyone still in simultaneously taps A or B.',
      'Answer wrong and you\'re eliminated; correct players survive to the next question.',
      'Players knocked out in the same round share a placement.',
      'Last survivor ranks first (reverse-elimination order).',
    ],
  },
  definitionDuel: {
    id: 'definitionDuel', name: 'Definition Duel', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.FIBBAGE_WRITE,
    description: 'Balderdash — invent a fake definition for a real obscure word, then spot the true one.',
    instructions: [
      'Each round reveals one real but obscure word — just the word, never its meaning.',
      'Write a fake-but-plausible definition convincing enough to fool everyone.',
      'All fakes plus the REAL definition are shuffled and shown with no names attached.',
      'Vote for the one you think is true — you can\'t pick your own bluff.',
      'Score +1000 for finding the truth and +500 per player your fake fools; most points after 4 rounds wins.',
    ],
  },
  quiplashClash: {
    id: 'quiplashClash', name: 'Quiplash Clash', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.FIBBAGE_WRITE,
    description: 'Head-to-head comedy write-off — answer prompts, the room votes the funnier of each duel.',
    instructions: [
      'Each prompt is a duel between two players — write the funniest answer to your prompts.',
      'For each duel you\'ll see two anonymous answers; tap the funnier one.',
      'You can\'t vote in a duel you wrote for, and authors stay hidden until the reveal.',
      'Each duel splits points by vote share, so a blowout pays its writer far more.',
      'Highest total across your duels wins; ties share a placement.',
    ],
  },
  captionThis: {
    id: 'captionThis', name: 'Caption This', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.FIBBAGE_WRITE,
    description: 'Caption AI-generated scenes, then vote the funniest caption that isn\'t your own.',
    instructions: [
      'Each round shows an AI-generated image — write the funniest one-line caption.',
      'Captions are shuffled and shown anonymously to everyone.',
      'Vote for the caption that made you laugh hardest — you can\'t vote your own.',
      'Score +100 for every vote your caption receives, across 4 images.',
      'Highest total after 4 rounds wins; ties share a placement.',
    ],
  },
  awkwardAward: {
    id: 'awkwardAward', name: 'Awkward Award', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.FIBBAGE_WRITE,
    description: 'Write an acceptance reason for a silly trophy — the room crowns the best combo.',
    instructions: [
      'Each round shows a ridiculous trophy.',
      'Write a short acceptance reason for why you deserve it.',
      'Reasons are pinned to random nominees and shown to everyone.',
      'Vote the best trophy + reason combo — you can\'t vote your own reason.',
      'The reason\'s author scores per vote; most points after 4 rounds wins.',
    ],
  },
  mostLikelyTo: {
    id: 'mostLikelyTo', name: 'Most Likely To', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: '"Who is most likely to ___?" — secret-vote a player, the most-voted gets crowned.',
    instructions: [
      'Each round shows a "Most likely to ___" prompt.',
      'Secretly vote for one player (you can even vote yourself).',
      'Votes stay secret until the reveal, shown one tally at a time.',
      'You earn points for every vote you receive that round.',
      'Highest total across 5 rounds ranks first; ties share a placement.',
    ],
  },
  voteProphet: {
    id: 'voteProphet', name: 'Vote Prophet', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Vote your real opinion, then predict what the group will pick — predict right to score.',
    instructions: [
      'Each round shows an opinion prompt with two sides.',
      'Lock in your real preference AND your prediction of the group\'s majority.',
      'After the reveal, you score only if your prediction matched the actual plurality.',
      'Everyone\'s choices stay private until the reveal.',
      'Highest total across 5 rounds wins; ties share a placement.',
    ],
  },
  groupMind: {
    id: 'groupMind', name: 'Group Mind', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Type an answer that MATCHES the others — score for every player you align with.',
    instructions: [
      'Each round shows an open category like "Name a pizza topping".',
      'Privately type one short answer, trying to match what others write.',
      'Answers are matched server-side (case/spacing-insensitive) and bucketed.',
      'You score for every other player whose answer lands in your bucket.',
      'Highest total across 5 rounds wins; ties share a placement.',
    ],
  },
  mobRule: {
    id: 'mobRule', name: 'Mob Rule', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Pick a side and try to land in the majority — but watch for twist rounds that flip it.',
    instructions: [
      'Each round shows an opinion prompt with two sides.',
      'A banner tells you whether this round rewards the MAJORITY or (twist!) the MINORITY.',
      'Secretly pick a or b.',
      'After the reveal, everyone on the rewarded side scores; an exact tie scores nobody.',
      'Highest total across 5 rounds wins; ties share a placement.',
    ],
  },
  twoTruths: {
    id: 'twoTruths', name: 'Two Truths and a Lie', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.FIBBAGE_WRITE,
    description: 'Each player tells two truths and a lie — everyone else hunts for the lie.',
    instructions: [
      'Each round one player is the storyteller and writes three statements — two true, one a lie.',
      'The three are shuffled and shown; everyone else secretly guesses the lie.',
      'Guessers score for catching the lie; the storyteller scores per player they fool.',
      'Which statement is the lie stays hidden until the reveal.',
      'Highest total after everyone has told their round wins; ties share a placement.',
    ],
  },
  superlativeShowdown: {
    id: 'superlativeShowdown', name: 'Superlative Showdown', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Privately rank the whole lobby on a superlative — the group consensus is the score.',
    instructions: [
      'Each round shows a superlative like "Most likely to survive a zombie apocalypse".',
      'Privately rank every player from most to least.',
      'Rankings are private until the reveal, then aggregated (Borda) into a consensus order.',
      'Your standing reflects how the whole group ranked you across all rounds.',
      'Most consensus points after 4 rounds ranks first; ties share a placement.',
    ],
  },
  spyfall: {
    id: 'spyfall', name: 'Spyfall', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'One secret spy hides among players who all share a hidden location.',
    instructions: [
      'Everyone but the spy secretly learns the location and a role — the spy sees neither.',
      'Discuss out loud: ask and answer questions to expose the spy without naming the location.',
      'Secretly vote the player you suspect is the spy (you can\'t vote yourself).',
      'If accused, the spy gets one last chance to guess the real location and steal the win.',
      'The spy wins if they escape the vote OR guess the location; otherwise the group wins.',
    ],
  },
  chameleon: {
    id: 'chameleon', name: 'Chameleon Clues', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Everyone shares a secret word on a grid except the hidden chameleon, who must bluff.',
    instructions: [
      'Everyone learns the secret word on the 4x4 grid — except the random chameleon, who sees only the theme.',
      'Everyone submits ONE word hinting at the secret word; the chameleon must fake a fitting clue.',
      'All clues go public, then everyone secretly votes who the chameleon is.',
      'If caught, the chameleon secretly picks the grid cell they think is the word.',
      'Chameleon wins if they escape the vote OR guess the word; otherwise the crew scores.',
    ],
  },
  traitorsVault: {
    id: 'traitorsVault', name: "Traitor's Vault", minPlayers: 4, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Co-op heist with hidden traitors — crack the vault while rooting out saboteurs.',
    instructions: [
      'You are secretly Loyal crew or a hidden Traitor (1 traitor at 4-5 players, 2 at 6-8).',
      'Each of 5 stages, privately pick Help or Sabotage — a stage cracks only if nobody sabotaged.',
      'You see the pass/fail and how many sabotaged, but never who.',
      'After stage 3 the crew holds one secret eject vote.',
      'Crack 4+ stages and Loyal players win; otherwise the Traitors do. Ejecting a traitor pays a bonus.',
    ],
  },
  whisperNetwork: {
    id: 'whisperNetwork', name: 'Whisper Network', minPlayers: 4, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Two secret factions tug a shared meter, then everyone guesses who is on which side.',
    instructions: [
      'You are secretly on the Red or Blue faction — Red wants the meter positive, Blue negative.',
      'Each of 5 rounds, privately push the meter (-2 to +2); only the running total is shown, never who pushed.',
      'Hide your hand: push too hard and you give yourself away.',
      'After 5 rounds, secretly tag every other player\'s faction.',
      'Your faction scores if the meter ends on your side, plus a bonus for every correct tag.',
    ],
  },
  sketchImpostor: {
    id: 'sketchImpostor', name: 'Sketch Impostor', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Everyone draws the same secret word one stroke at a time — except the wordless impostor.',
    instructions: [
      'Everyone shares a secret word except one random impostor, who has no word.',
      'Take turns adding ONE stroke each to a shared drawing — the impostor must fake a convincing line.',
      'After two strokes each, everyone votes who the impostor is.',
      'If caught, the impostor can still steal the win by naming the secret word.',
      'Catch the impostor to score as the crew; survive or guess the word to score as the impostor.',
    ],
  },
  takeSix: {
    id: 'takeSix', name: 'Take Six', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Play cards into rows — get stuck with the 6th and you eat the bullheads. Fewest wins.',
    instructions: [
      'Everyone holds 10 cards. Four rows each start with one card.',
      'Each round, everyone secretly picks one card; they resolve in ascending order.',
      'A card joins the row whose end is the highest value still below it.',
      'Place the 6th card in a row and you take the first 5 as penalty bullheads.',
      'Lowest total bullheads after 10 rounds wins.',
    ],
  },
  pressYourLuckPigs: {
    id: 'pressYourLuckPigs', name: 'Press Your Luck Pigs', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Roll to build a pot — but roll a 1 and lose it all. Bank before you bust.',
    instructions: [
      'On your turn, roll the die to add to your turn pot — as many times as you dare.',
      'Roll a 1 and you BUST: the whole turn pot is lost and your turn ends.',
      'Bank any time to add the pot to your score and pass the dice.',
      'The die is server-rolled — pure nerve, no skill in the roll.',
      'First to 100 (after the round completes) wins; highest score ranks first.',
    ],
  },
  qwixx: {
    id: 'qwixx', name: 'Qwixx', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Roll-and-write — mark numbers across four colour rows, but only left to right.',
    instructions: [
      'You have four colour rows: red & yellow ascending, green & blue descending.',
      'Each round the server rolls and offers a number.',
      'Mark that number on one row — but only to the right of your last mark in it — or pass.',
      'More marks in a row score triangularly (1, 3, 6, 10, 15…).',
      'Highest total across the rows after 12 rounds wins.',
    ],
  },
  yahtzee: {
    id: 'yahtzee', name: 'Yahtzee', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Roll five dice, keep the best, and fill your scorecard across 13 turns.',
    instructions: [
      'Each turn, roll five dice, then re-roll any you don\'t keep up to twice.',
      'Assign your final dice to one of 13 categories (each used once).',
      'Chase three/four of a kind, full house, straights, and the 50-point Yahtzee.',
      'A 63+ upper section earns a 35-point bonus.',
      'Highest grand total after 13 turns wins.',
    ],
  },
  dominoDrift: {
    id: 'dominoDrift', name: 'Domino Drift', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Match pips to extend the train — first to empty their hand wins.',
    instructions: [
      'Everyone is dealt seven dominoes (kept private).',
      'On your turn, play a tile matching an open end of the train, or draw from the boneyard.',
      'If you still can\'t play (and the boneyard is empty), pass.',
      'First to empty their hand ends the game.',
      'Everyone else is ranked by the fewest pips left in hand.',
    ],
  },
  bingoBrawl: {
    id: 'bingoBrawl', name: 'Bingo Brawl', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Daub your card as numbers are called — first to a full line shouts BINGO.',
    instructions: [
      'You get a private 5x5 card with a free centre space.',
      'The server calls a new number every few seconds.',
      'Tap a cell to daub it — only numbers that were actually called count.',
      'Complete any row, column, or diagonal and hit BINGO to claim it.',
      'Finish order is your placement; daub count breaks ties.',
    ],
  },
  twentyFour: {
    id: 'twentyFour', name: 'Twenty-Four', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Race to make 24 from four numbers using + − × ÷ and parentheses.',
    instructions: [
      'Each deal shows the same four numbers (1–9) — a way to make 24 always exists.',
      'Build an expression using each number exactly once that equals 24.',
      'Tap the number/operator pad or type it, then submit — the server checks your math.',
      'Faster correct answers score more; wrong tries don\'t lock you out.',
      'Highest total over 4 deals wins; ties share a placement.',
    ],
  },
  targetLocked: {
    id: 'targetLocked', name: 'Target Locked', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Countdown numbers — combine six numbers to land as close to the target as you can.',
    instructions: [
      'Each round deals six source numbers and a random 3-digit target.',
      'Build an expression (+ − × ÷ and parentheses) using each number at most once.',
      'Every intermediate result must be a positive whole number.',
      'Submit as often as you like — only your closest attempt counts.',
      'Closer is worth more; highest total over 3 rounds wins.',
    ],
  },
  factorFrenzy: {
    id: 'factorFrenzy', name: 'Factor Frenzy', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Tap every true divisor of the target before the window closes — wrong taps cost you.',
    instructions: [
      'Each window shows a big target number and a grid of candidate numbers.',
      'Tap every number that divides the target evenly for points + a streak bonus.',
      'Tapping a non-divisor costs points and breaks your streak.',
      'Each grid number can be tapped once; the window is short.',
      'Highest cumulative score over 8 windows wins; ties share a placement.',
    ],
  },
  goingOnce: {
    id: 'goingOnce', name: 'Going Once', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Live ascending auction — bid up 6 face-up lots, win the most value before your cash runs out.',
    instructions: [
      'Everyone starts with 100 coins. Six face-up lots (worth 5–40) come up one at a time.',
      'Tap RAISE to become the high bidder; the price climbs +5 each time (only if you can afford it).',
      'A 6-second "going once" countdown resets on every raise.',
      'When it runs out, the high bidder pays their bid and wins the lot\'s value.',
      'Most total value after 6 lots wins; leftover cash breaks ties — cheap wins beat overpaying.',
    ],
  },
  dutchDrop: {
    id: 'dutchDrop', name: 'Dutch Drop', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Descending auction — grab a mystery lot before the price drops too far, or a rival snaps it.',
    instructions: [
      'You start with 100 coins; six mystery lots are auctioned one at a time.',
      'Each lot\'s price starts high and ticks DOWN every second.',
      'Hit BUY to claim it at the current price — the first affordable buyer wins.',
      'The hidden value is revealed only after it sells; profit = value − price.',
      'Highest total profit after 6 lots wins; ties share a placement.',
    ],
  },
  sealedVault: {
    id: 'sealedVault', name: 'Sealed Vault', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Sealed-bid auction — secretly bid on mystery lots; highest bidder pays and pockets the loot.',
    instructions: [
      'You start with 100 coins. Each of 5 rounds puts a mystery lot (worth a hidden 20–80) on the block.',
      'Everyone secretly submits one sealed bid (up to your bankroll).',
      'Bids resolve together; the highest bidder pays their bid and wins the lot\'s value.',
      'You can never bid more than you hold, and bids stay hidden until the reveal.',
      'Most total loot after 5 lots wins; leftover bankroll breaks ties.',
    ],
  },
  lastBidStanding: {
    id: 'lastBidStanding', name: 'Last Bid Standing', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'All-pay war of attrition — everyone who stays in pays each tick; last one standing takes the jackpot.',
    instructions: [
      'One jackpot is up for grabs; everyone starts with a bankroll.',
      'Each tick, choose RAISE or DROP — everyone who raises PAYS the tick cost (even if they lose).',
      'Once you drop, you\'re out for good; can\'t afford the tick = auto-drop.',
      'The last player still in wins the jackpot.',
      'Drop order (reversed) is your placement — last standing ranks first.',
    ],
  },
  tokenTussle: {
    id: 'tokenTussle', name: 'Token Tussle', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Colonel Blotto — secretly split 20 tokens across 5 fronts; win each front by committing the most.',
    instructions: [
      'Each round there are 5 fronts, each worth a prize.',
      'Privately distribute up to 20 tokens across the fronts.',
      'For each front, whoever committed the most tokens wins its prize (ties split it).',
      'Allocations are secret until the reveal.',
      'Highest total over 3 rounds wins; ties share a placement.',
    ],
  },
  whackAPharaoh: {
    id: 'whackAPharaoh', name: 'Whack-a-Pharaoh', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Real-time whack-a-mole — smack pharaohs, dodge mummies. Most points in 25s wins.',
    instructions: [
      'Pharaohs and mummies pop out of nine holes for about a second each.',
      'Whack a pharaoh for +100; whack a mummy and you lose 60 (never below 0).',
      'Everyone races the SAME pop-ups at once and scores independently — speed is everything.',
      'Tapping an empty or cleared hole does nothing; each target scores once.',
      'Highest score after the 25-second flurry wins; ties share a placement.',
    ],
  },
  coinCascade: {
    id: 'coinCascade', name: 'Coin Cascade', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Slide your basket across 5 lanes to catch coins and gems, dodge bombs. Most points wins.',
    instructions: [
      'Coins, gems, and bombs rain down 5 lanes from a shared stream.',
      'Tap a lane to slide your basket (it starts in the middle).',
      'Catch coins (+10) and gems (+25) when they reach the catch line in your lane.',
      'Bombs are −15 — slide out of the way. Score never drops below 0.',
      'Highest score after ~30 seconds wins; ties share a placement.',
    ],
  },
  balloonBrinkmanship: {
    id: 'balloonBrinkmanship', name: 'Balloon Brinkmanship', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Pump your balloon for air — but a hidden burst threshold means one pump too many pops it.',
    instructions: [
      'Each round your balloon starts empty and has a SECRET burst threshold you can\'t see.',
      'Tap PUMP to add air — more air scores more, but inches you toward the pop.',
      'Tap BANK to lock your current air into your score and sit out safely.',
      'Pump over the hidden threshold and it POPS — you bank nothing that round.',
      'Highest total air after 4 rounds wins; ties share a placement.',
    ],
  },
  pulseTap: {
    id: 'pulseTap', name: 'Pulse Tap', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Rhythm tapping — nail the beat for Perfects and build a combo across 3 tightening rounds.',
    instructions: [
      'Beats sweep toward a hit-line; tap right on the beat.',
      'Perfect timing scores most, a near-miss less, way off is a Miss.',
      'Consecutive hits build a combo multiplier.',
      'Each round\'s beat gets tighter and faster.',
      'Highest score over 3 rounds wins; ties share a placement.',
    ],
  },
  bullseyeDrop: {
    id: 'bullseyeDrop', name: 'Bullseye Drop', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Timing-precision darts — release as the reticle hits the bullseye. Most points over 5 darts wins.',
    instructions: [
      'A reticle pulses in and out across concentric rings.',
      'Tap RELEASE the instant it\'s smallest to hit the bullseye (+100).',
      'Outer rings score less; the timing is server-judged so it\'s fair.',
      'You get 5 darts, and the reticle speeds up each throw.',
      'Highest total wins; ties share a placement.',
    ],
  },
  hotPotatoRelay: {
    id: 'hotPotatoRelay', name: 'Hot Potato Relay', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Pass the bomb before its hidden fuse blows — whoever holds it when it goes is out.',
    instructions: [
      'A bomb with a HIDDEN fuse starts with one player.',
      'If you hold it, tap PASS to hand it to the next player — fast.',
      'When the fuse blows, whoever holds the bomb is eliminated.',
      'A new hidden fuse starts and play continues among the survivors.',
      'Last player standing wins; elimination order (reversed) sets the placements.',
    ],
  },
  echoChamber: {
    id: 'echoChamber', name: 'Echo Chamber', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Simon-style memory race — repeat the growing sequence; one wrong tap and you\'re out.',
    instructions: [
      'Four colour pads flash a sequence; one new step is added each round.',
      'Watch during SHOW, then tap the pads back in the exact order during INPUT.',
      'The sequence is never shown again while you tap — you must remember it.',
      'One wrong tap eliminates you at your current depth.',
      'Longest sequence reproduced ranks first; ties share a placement.',
    ],
  },
  gridLock: {
    id: 'gridLock', name: 'Grid Lock', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: '15-puzzle race — slide the tiles back into order before your rivals do.',
    instructions: [
      'Everyone starts from the same scrambled 4x4 grid (1–15 plus a gap).',
      'Tap a tile next to the gap to slide it in.',
      'Get the board to 1–15 in order with the gap bottom-right to solve.',
      'First to solve places 1st, then the next, and so on.',
      'At the timer, unsolved players rank by tiles in the correct spot.',
    ],
  },
  nonogramDash: {
    id: 'nonogramDash', name: 'Nonogram Dash', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Picross solve-race — fill the hidden 8×8 picture from the row and column clues.',
    instructions: [
      'Each number clue lists the lengths of the filled runs in that row or column.',
      'Tap a cell to fill it; use Mark Empty to cross out blanks.',
      'You solve when your filled cells exactly match the hidden picture.',
      'First to solve places 1st; the server validates every solve.',
      'At the timer, unsolved players rank by correct cells.',
    ],
  },
  pairHunt: {
    id: 'pairHunt', name: 'Pair Hunt', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'SET, real-time — spot a trio where every attribute is all-same or all-different.',
    instructions: [
      'Twelve attribute-cards are on the table (shape, colour, count, fill).',
      'A valid SET is 3 cards where, for every attribute, the values are all same or all different.',
      'Tap 3 cards and claim — a valid set scores and is replaced; an invalid one briefly locks you out.',
      'The server checks every claim against the live tableau.',
      'Most valid sets wins; ties share a placement.',
    ],
  },
  crackTheVault: {
    id: 'crackTheVault', name: 'Crack the Vault', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Numeric Mastermind race — crack the hidden 4-digit code from locked/loose feedback.',
    instructions: [
      'Everyone races to crack the same hidden 4-digit code.',
      'Each guess returns how many digits are correct AND in place ("locked") and correct but misplaced ("loose").',
      'Use the feedback to deduce the code.',
      'First to get four locked cracks it and places 1st.',
      'At the timer, non-crackers rank by best progress then fewest guesses.',
    ],
  },
  sudokuSixer: {
    id: 'sudokuSixer', name: 'Sudoku Sixer', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: '6×6 mini-sudoku race — fill the grid so every row, column and 2×3 box holds 1–6.',
    instructions: [
      'Everyone solves the same 6x6 puzzle (digits 1–6).',
      'Tap a non-given cell and pick a digit; given cells are locked.',
      'Each row, column, and 2x3 box must contain 1–6 exactly once.',
      'First to match the full solution places 1st.',
      'At the timer, unsolved players rank by correct cells.',
    ],
  },
  flashFlood: {
    id: 'flashFlood', name: 'Flash Flood', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Pattern-memory race — reproduce the flashed grid; the grid grows each round.',
    instructions: [
      'Each round a pattern of cells lights up, then hides.',
      'Tap exactly the cells that were lit (and no extras) to bank the round.',
      'A wrong or incomplete recall eliminates you at that round.',
      'The grid grows bigger every round.',
      'Most rounds banked ranks first; ties share a placement.',
    ],
  },
  sequenceSleuth: {
    id: 'sequenceSleuth', name: 'Sequence Sleuth', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Guess the next number — the fewer terms you need, the more you score.',
    instructions: [
      'A hidden number sequence reveals its terms one at a time.',
      'Lock in your guess for the NEXT term whenever you\'re confident.',
      'Guessing correctly with fewer terms shown scores more.',
      'A wrong guess locks you out of that sequence.',
      'Highest total across 5 sequences wins; ties share a placement.',
    ],
  },
  oneLineWonder: {
    id: 'oneLineWonder', name: 'One-Line Wonder', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Draw the secret word in a single unbroken line, then rate everyone else\'s masterpiece.',
    instructions: [
      'A secret word is revealed — everyone draws the SAME word.',
      'You get ONE unbroken stroke: lift your pen and your drawing locks in.',
      'Submit your one-line masterpiece before the timer runs out.',
      'Then privately give every other drawing 1–5 stars (you can\'t rate your own).',
      'Most stars received wins; ties share a placement.',
    ],
  },
  copyThat: {
    id: 'copyThat', name: 'Copy That', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Memorise a flashed drawing, then redraw it — scored by shape similarity, no voting.',
    instructions: [
      'Each round flashes a simple reference drawing for a few seconds — memorise it.',
      'When it vanishes, redraw it from memory on a blank canvas and submit.',
      'The server scores your sketch by overlap with the original — closer shapes score higher.',
      'The reference and everyone\'s drawing are revealed with a similarity percent.',
      'Highest cumulative similarity over 3 rounds wins; ties share a placement.',
    ],
  },
  captionClash: {
    id: 'captionClash', name: 'Caption Clash', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Draw an absurd doodle, caption a rival\'s, then vote the funniest doodle+caption combo.',
    instructions: [
      'Everyone doodles the same silly prompt — you only see your own canvas.',
      'You\'re handed someone else\'s doodle and write a funny caption for it.',
      'Every doodle+caption pair is shown anonymously; vote the funniest (not your own).',
      'Each vote scores BOTH the artist and the caption writer.',
      'Most points wins; ties share a placement.',
    ],
  },
  exquisiteCorpse: {
    id: 'exquisiteCorpse', name: 'Exquisite Corpse', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Everyone draws one horizontal band of a shared monster, then votes the best band.',
    instructions: [
      'The canvas is split into horizontal bands — you draw only in yours.',
      'You see just a thin sliver of the band above to connect to — never the rest.',
      'Draw your band and submit; your pen is clamped to your strip.',
      'The full composite monster is revealed and everyone votes the best band (not their own).',
      'Most votes for your band wins; ties share a placement.',
    ],
  },
  traceRace: {
    id: 'traceRace', name: 'Trace Race', minPlayers: 2, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Trace the target path as accurately as you can — scored by coverage vs spillover, no voting.',
    instructions: [
      'A faint target path is shown on your canvas.',
      'Trace over it as accurately as you can before time runs out.',
      'The server scores your trace by how much of the path you covered minus how far you strayed.',
      'It\'s pure dexterity — no voting, just accuracy.',
      'Highest score wins; ties share a placement.',
    ],
  },
  ransomNote: {
    id: 'ransomNote', name: 'Ransom Note', minPlayers: 3, maxPlayers: 8,
    turnTimer: TIMERS.CARD_GAME,
    description: 'Convey a secret word using only emoji from your hand, then vote the cleverest note.',
    instructions: [
      'Each round you\'re dealt a hand of random emoji and a secret word.',
      'Arrange 3–5 emoji into a "ransom note" that conveys the word — without writing it.',
      'All notes are shown anonymously beside the revealed word.',
      'Vote the cleverest note (you can\'t vote your own).',
      'Most votes over the rounds wins; ties share a placement.',
    ],
  },
};

export function getEligibleGames(playerCount) {
  return Object.values(GAMES).filter(
    (g) => playerCount >= g.minPlayers && playerCount <= g.maxPlayers
  );
}
